name: sleuth_prep
description: |
  Import kallisto/salmon counts in Sleuth
authors:
  - Thibault Dayris
input:
  - TSV formatted target mapping
  - TSV formatted experimental design
  - List of salmon quantification directories
output:
  - RDS formatted sleuth object
