---
name: Forest Plot
url: https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#95_Comparing_two_cohorts_(MAFs)
description: Compare two maf cohorts and build a forest plot
authors:
  - Thibault Dayris
input:
  - maf: List of two maf RDS-formatted files
output:
  - png: PNG formatted forest plot
  - tsv: TSV-formatted compared maf files
