---
name: bwa_fixmate
description: Map your reads with BWA and fix mates right after
authors:
  - Thibault Dayris
input:
  - Fasta formatted genome sequence
  - Fastq formatted reads
output:
  - Bam formatted mapped reads
