---
name: Chipseq
description: Perform various analyses on Chipseq
authors:
  - Thibault Dayris
input:
  - Fastq files
output:
  - Peak called
usage:
  - \# Go to your directory containing VCF files
  - cd /path/to/project
  - \# Copy/paste the following line for **HG38**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/chipseq/run.sh
