---
name: mixcr export alignment
description: export alignment results from a binary file (.vdjca) to a human-readable text file with `mixcr <https://mixcr.readthedocs.io/en/master/export.html#export>`_
authors:
  - Thibault Dayris
input:
  - Alignments in vdjca format
output:
  - TSV-formetted text file
