---
name: cnv_facets
description: Run cnv_facets
authors:
  - Thibault Dayris
input:
  - Bam input:
    - Bam formatted Tumor mapped reads
    - Bam formatted Normal mapped reads
    - Known VCF file
  - Pileup input:
    - Pileup with normal first, tumor in second
output:
  - VCF formatted copy number variants
  - PNG formatted CNV plot
  - PNG formatted coverage plot
  - PNG formatted spider plot
  - CSV formatted Pileup if bam files were provided in input
