---
name: iRODS copy
description: This wrapper performs iRODS copy from a file url
authors:
  - Thibault Dayris
input:
  - None
output:
  - The expected downloaded file
notes: |
  Parameters:

  * remote_extra (dict): Extra parameters for remote
  * input (string): A file to get from iRODS
