---
name: Coverage plot
description: Build a coverage plot over the genome with ChipSeeker
authors:
  - Thibault Dayris
input:
  - A RDS formatted file containing peaks as GRanges or GRangesList
output:
  - A PNG formatted coverage plot
notes: |
  notes
