---
name: make_logit_model
description: Build a model from hexamer_table
authors:
  - Thibault Dayris
input:
  - Hexamer table
  - Coding and non-coding fasta formatted transcripts sequences
  - Fasta formatted genome sequence (if transcript sequences were not provided)
output:
  - CPAT model
