---
name: DESeqDataSetFromMatrix
description: Load a count table, a coldata, and a formula and return a DESeq Dataset.
authors:
  - Thibault Dayris
input:
  - counts: A TSV-formatted count table
  - coldata: A TSV-formatted experimental design description
output:
  - dds: A RDS-formatted DESeq2 Dataset
notes: |
  Provide the formula as a parameter in "extra": " design = ~ condition "

  Provide the name of the column containing gene names in your count matrix
  with the paramerer : `count_gene_col`.

  Provide the minimum counts accepted in your count matrix with the parameter:
  `count_filter`.
