---
name: vcf-match
description: Annotate for each variant in a VCF/BCF at STDIN whether it is contained in a given second VCF/BCF using `rust bio tools <https://github.com/rust-bio/rust-bio-tools>`_.
authors:
  - Thibault Dayris
input:
  - One calling file to annotate, either VCF or BCF formatted
  - One reference call used to annotate, either VCF or BCF formatted.
output:
  - An annotated VCF file
