---
name: MultiQC_RNASeq_Report
description: Build a result report for RNASeq analysis
authors:
  - Thibault Dayris
input:
  - clustermap_sample: Optional clustered heatmap of all samples
  - clustermap_genes: Optional clustered heatmap of DEG
  - pca_axes_correlation: Optional barplot of the correlation between samples and experimental design factors.
  - pairwise_scatterplot: Optional pairwise scatterplot
  - pca_plot: Optional PCA
  - volcanoplot: Optional volcano plot
  - distro_expr: Optional distribution of genes expression per sample
  - ma_plot: Optional MA-Plot
  - consensus_cluster_plus: Optional consensus_cluster_plus result
  - titv_plot: Optional Ti/Tv plot from maftools
  - maf_summary: Optional maf summary
  - oncoplot: Optional oncoplot
output:
  - multiqc_config: Path to a yaml file that holds MultiQC config
  - plots: A list of graphs depending on the input files
params:
  - title: Optional report title
  - subtitle: Optional report subtitle
  - intro_text: Optional intro text,
  - report_comment: Optional comment,
  - show_analysis_paths: Boolean. Display (default) or hide results paths on the computing machine.,
  - show_analysis_time: Boolean. Display (default) or hide computation times.
  - custom_logo: Optional path to a PNG logo,
  - custom_logo_url: Optional path to a web page,
  - custom_logo_title: Optional text as a replacement of the logo.,
  - report_header_info:
      - Contact E-mail: An optional email address
      - Application Type: Optional type of analysis
      - Project Type: Optional kind of analysed project
      - Sequencing Platform: Optional info towards the sequencing platform
      - Sequencing Setup: Optional info about the sequencing kit/method
