---
name: pcaExplorer launching script
description: Write the Rscript used to start pcaExplorer
authors:
  - Thibault Dayris
input:
  - A normalized dds (vst/rlog) of all samples and targets
  - A DESeq2 dataset
output:
  - A R script
notes: |
  Do not forget to load required environment before using the produced script
