name: cluster profiler enricher
description: Perform gene term enrichment analysis with Cluster Profiler
url: https://yulab-smu.top/biomedical-knowledge-mining-book/universal-api.html
authors:
  - Thibault Dayris
input:
  - gene: Two columned dataset, containing `gene_id \t weight`. These ids must match with the ones provided in `term2gene`.
  - term2gene: Enrichment term <-> gene id mapping file. Either a TSV-formatted text file, a GMT-formatted text file, or a R `data.frame` as RDS binary file with two columns `term \t gene`.
  - term2name: Optional enrichment term <-> enrichment name mapping file. TSV/CSV formatted. Either a TSV text file, or a R dataframe as RDS binary file with two column `term \t name`.
output:
  - tsv: Enrichment analysis result as a TSV formatted text file.
  - rds: Enrichment analysis result as a RDS formatted binary file.
  - barplot: Enrichment analysis result as a PNG formatted image representing a barplot of selected/best enriched terms.
  - dotplot: Enrichment analysis result as a PNG formatted image representing a dotplot of selected/best enriched terms.
  - cnetplot: Linkage of gene and terms, as a PNG formatted image representing a concept network of enriched terms.
  - heatplot: Linkage of gene and terms, as a PNG formatted image representing a coloured heatmap.
  - emapplot: Linkage of terms, as PNG formatted image representing the network.
  - upsetplot: Linkage of gene and terms, as a PNG formatted image representing up-sets.
  - pmcplot: Pubmed central trend plot, as a PNG formatted image.
params:
  - enrich_extra: Optional parameters for `clusterprofiler::enricher <https://rdrr.io/bioc/clusterProfiler/man/enricher.html>`_ .
  - png_extra: Optional parameters for `grDevices::png <https://www.rdocumentation.org/packages/grDevices/versions/3.4.1/topics/png>`_ .
  - barplot_extra: Optional parameters for `graphics::barplot <https://rdrr.io/r/graphics/barplot.html>`_ .
  - dotplot_extra: Optional parameters for `enrichplot::dotplot <https://rdrr.io/bioc/enrichplot/man/dotplot.html>`_ .
  - cnetplot_extra: Optional parameters for `enrichplot::cnetplot <https://rdrr.io/bioc/enrichplot/man/cnetplot.html>`_ .
  - heatplot_extra: Optional parameters for `enrichplot::heatplot <https://rdrr.io/bioc/enrichplot/man/heatplot.html>`_ .
  - emapplot_extra: Optional parameters for `enrichplot::emapplot <https://rdrr.io/bioc/enrichplot/man/emapplot.html>`_ .
  - upsetplot_extra: Optional parameters for `enrichplot::upsetplot <https://rdrr.io/bioc/enrichplot/man/upsetplot-methods.html>`_ .
  - pmcplot_extra: Optional parameters for `enrichplot::pmcplot <https://rdrr.io/bioc/enrichplot/man/pmcplot.html>`_ .
notes: |
  * The universe corresponds to the list of genes provided in term2gene. (default ClusterProfiler behavior)