---
name: wisecondorx newref
description: Create reference with WisecondorX
authors:
  - Thibault Dayris
input:
  - aln: List of reference samples
output:
  - Path to reference npz file
params:
  - extra: Extra parameters for wisecondorx newref, besides `--cpus`.
