---
name: bcf2fastq
description: Run demultiplexing of base call (BCL) files into Fastq files
authors:
  - Thibault Dayris
input:
  - Directory containing bcl files or whole illumina run
output:
  - Directory containing fastq files
