name: computeMatrix
description: |
  Calculate scores per genome regions and prepare intermediate
  files for DeepTools
authors:
  - Thibault Dayris
input:
  - bigWig formatted coverage file
  - BED/GTF/GFF formatted genomic regions of interest
  - An optional BED formatted blacklisted regions
output:
  - Matrix with values underlying the heatmap
  - Gziped archive with values underlying the profile
  - BED file with regions
notes: |
  Output files are optional, use gzip, matrix, and/or regions keywords in
  output section to (dis)enable each of them.
