channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - conda-forge:r-base ==3.6.3
  - conda-forge:r-devtools ==2.4.1
  - conda-forge:r-dbi ==1.1.1
  - conda-forge:r-rsqlite ==2.2.5
  - conda-forge:r-rmarkdown ==1.12
  - bioconda:r-eacon ==0.3.4_1
  - bioconda:bioconductor-bsgenome ==1.54.0
  - bioconda:bioconductor-bsgenome.hsapiens.ucsc.hg19 ==1.4.0
  - bioconda:bioconductor-bsgenome.hsapiens.ucsc.hg38 ==1.4.1
  - bioconda:bioconductor-bsgenome.hsapiens.1000genomes.hs37d5 ==0.99.1
  - bioconda:bioconductor-affxparser ==1.58.0
  - bioconda:bioconductor-biostrings ==2.54.0
  - bioconda:bioconductor-aroma.light ==3.16.0
  - bioconda:bioconductor-copynumber ==1.26.0
  - bioconda:bioconductor-genomicranges ==1.38.0
  - bioconda:bioconductor-rhdf5 ==2.30.0
  - bioconda:bioconductor-limma ==3.42.0
  - bioconda:r-sequenza ==3.0.0
  - bioconda:r-facets ==0.5.14
  - bioconda:cnv_facets ==0.16.0
  - bioconda:ascat ==2.5.2
  - conda-forge:r-foreach ==1.5.1
  - conda-forge:r-dplyr ==1.0.6
