---
name: EaCoN_segment
description: Segment profile with EaCoN
authors:
  - Thibault Dayris
input:
  - RDS processed file
output:
  - RDS segmented file
notes: |
  Use extra parameters to pass options to segment.ff
