channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-txdb.mmusculus.ucsc.mm10.ensgene ==3.4.0
  - bioconda::bioconductor-chipseeker ==1.28.3
  - bioconda::bioconductor-org.mm.eg.db ==3.13.0
