---
name: somatic interactions
url: https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#91_Somatic_Interactions
description: Mutually exclusive or co-occurring set of mutated genes within the top 10 mutated genes
authors:
  - Thibault Dayris
input:
  - rds: RDS-formatted maf file
output:
  - png: PNG-formatted exclusive/co-occurring mutated genes
notes: |
  notes
