name: Pairgrid
description: Subplot grid for plotting pairwise relationships in a dataset.
url: https://seaborn.pydata.org/generated/seaborn.PairGrid.html#seaborn.PairGrid
authors:
  - Thibault Dayris
input:
  - tsv: A TSV, or multiple TSV files that are being merged
output:
  - png: Path to PNG pair grid.
params:
  - key: Name of the key on which to merge TSV files.
  - x_axis: The name of the column to put as x axis.
  - y_axis: The name of the column to put as y axis.
  - color: The name of the column used to color the dots.
  - size: The name of the column used to set the dots' size.
  - subplots: The name of the subplots
