---
name: bioinfokit
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioinfokit=1.0.0
  - numpy=1.19.2
  - pandas=1.1.3
  - matplotlib=3.3.2
  - seaborn=0.11.0
  - matplotlib-venn=0.11.5
  - adjusttext=0.7.3.1
