---
name: Bioinfokit Volcanoplot
description: Build a volcanoplot from a TSV file with Bioinfokit
authors:
  - Thibault Dayris
input:
  - A table containing pvalues and fold changes
output:
  - A PNG-formatted volcano plot
notes: |
  Use parameters in Snakefile to pass options to python functions with dictionnaries

  * read_csv Dict[str, Any]: Arguments to pandas.read_csv(). Do not set: `filepath_or_bufferstr`, or `sep`.
  * volcano Dict[str, Any]: Arguments to bioinfokit.visuz.gene_exp.volcano(). Do not set: `df`, `figtype`, `figname`, or `show`.
