---
name: variant occurence sample
description: Find occurence of variants within a sample
authors:
  - Thibault Dayris
input:
  - calls: A (list of) VCF-formatted file(s) to extract variants from
output:
  - txt: A TSV-formatted text file containing chr, start, stop, ref, alt
notes: |
  Multiallelic sites *must* be splitted before this occurence analysis. They are
  treated as a single variant in this wrapper.
