name: SnpSift Extract All Fields
url: https://pcingola.github.io/SnpEff/ss_extractfields/
description:  Convert from VCF to TSV with `SnpSift <https://pcingola.github.io/SnpEff/ss_extractfields/>`_
authors:
  - Thibault Dayris
input:
  - VCF/BCF, gzipped or not, that are to be formatted
output:
  - TSV-formatted extracted fields
