name: SnpSift Extract Fields
description:  Convert from VCF to TSV with `SnpSift <https://pcingola.github.io/SnpEff/ss_extractfields/>`_
authors:
  - Thibault Dayris
input:
  - VCF/BCF, gzipped or not, that are to be formatted
output:
  - TSV-formatted extracted fields
note: |
  Mendatory parameter:

  * fields (list[str]): A list of fiels to extract. See documentation for more information.
