channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge::r-dplyr
  - conda-forge::r-ggplot2
  - conda-forge::r-tidyr
  - conda-forge::r-tibble
  - bioconda::r-immunedeconv
  - conda-forge::r-readr
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-randomcolor
