---
name: cibersort-abs
description: Use Cibersort Absolute to deconvolute gene expression onto cell types
authors:
  - Thibault Dayris
input:
  - Quantification table
  - Cibersort expression matrix
  - Cibersort binary
output:
  - TSV and PNG formatted results
