---
name: GSEA MSigDB
description: Perform GSEA analysis on MSigDB
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the enrichment based on MSigDB
  - A TSV file containing the enrichment based on MSigDB
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  see available organisms from MSigDB with:
  msigdbr_show_species()

  Parameters:
    * msigdb_extra: Extra parameters for msigdbr::msigdbr
    * organism: Either Hs or Mm
