---
name: make linked txome
description: Build a meta data file for your genome index
authors:
  - Thibault Dayris
input:
  - A GTF formatted genome annotation
  - A Fasta formatted transcriptome sequences
output:
  - A metadata BiocFile
  - A json-formatted metadata file
notes: |
  If GTF and/or FASTA are provided as HTTP/FTP addresses, the files will be downloaded.
