---
name: tximeta make linked txome
description: Build metadata for a given genome, to annotate future quantifications
authors:
  - Thibault Dayris
input:
  - fasta: Path to transcriptome/genome sequences, fasta formatted. This can be a list of fasta files, or a single one.
  - gtf: Path to genome annotation, gtf formatted.
output:
  - json: Path to linked transcriptome and its metadata
params:
  - source: the source of transcriptome (e.g. "de-novo", "GENCODE", "Ensembl", "LocalEnsembl", ...). Default: "Local"
  - organism: organism (e.g. "Homo sapiens"). Default: "none"
  - release: release number (e.g. "27"). Default: "none"
  - genome: genome (e.g. "GRCh38"). Default: "none"
notes: |
  Leaving parameters to default arguments negates all advantages of tximeta over tximport or other transcript-count aggregators.
