design: design.tsv
fastp:
  fastp_extra: ''
ref:
  cosmic: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.bgz
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/capture_kit/ampliseq/hg38/hglft_www_2d6a7_9d3a70.hg38.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg38/somatic-hg38_af-only-gnomad.hg38.vcf.gz
  dbnsfp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz
threads: 20
fastq_screen:
  database:
    Contaminants:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters"
    Arabidopsis_thaliana.TAIR10:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis"
    BDGP6:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila"
    Ecoli:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli"
    Homo_sapiens.GRCh38:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human"
    Lambda:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda"
    mitochondria:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria"
    Mus_musculus.GRCm38:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse"
    phi_plus_SNPs:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX"
    Rnor_6.0:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat"
    GRCm38_rRNA:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA"
    Vectors:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors"
    Worm:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm"
    Yeast:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast"
  aligner_paths:
    bowtie2: bowtie2
