design: design.tsv
fastp:
  fastp_extra: ''
ref:
  cosmic: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/hg19/144_20150605/All_20150605.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh37.75/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG19/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg19-trim.vcf.gz
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh37.75/
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/capture_kit/ampliseq/hg19/hglft_www_2d6a7_9d3a70.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg19/somatic-b37_af-only-gnomad.raw.sites.vcf.gz
  dbnsfp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh37/dbNSFP4.1a.txt.gz
threads: 20
fastq_screen:
  database:
    Contaminants:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters"
    Arabidopsis_thaliana.TAIR10:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis"
    BDGP6:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila"
    Ecoli:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli"
    Homo_sapiens.GRCh38:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human"
    Lambda:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda"
    mitochondria:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria"
    Mus_musculus.GRCm38:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse"
    phi_plus_SNPs:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX"
    Rnor_6.0:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat"
    GRCm38_rRNA:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA"
    Vectors:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors"
    Worm:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm"
    Yeast:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast"
  aligner_paths:
    bowtie2: bowtie2
