design: design.tsv
fastp:
  fastp_extra: ''
snpeff_snpsift:
  snpeff_extra: -noLog -nodownload -lof
  snpsift_kaviar: -name 'Kaviar_' -exists 'ExistsInKaviar' -tabix -noDownload -noLog
  snpsift_cosmic: -name 'cosmic_' -exists 'ExistsInCosmic' -tabix -noDownload -noLog
  snpsift_dbsnp: -name 'dbSNP_' -exists 'ExistsInDBsnp' -tabix -noDownload -noLog
  snpsift_clinvar: -name 'clinvar_' -exists 'ExistsInClinVar' -tabix -noDownload -noLog
  snpsift_gnomad: -name 'gnomad_' -exists 'ExistsInGnomAD' -tabix -noDownload -noLog
  snpsift_dbnsfp: -noDownload -noLog -f 'hg18_chr,hg18_pos(1-based)' -n -g mm10
  snpsift_gwascat: -g mm10 -noDownload -noLog
  vcf_to_tsv_extra: "-e '.' -s $'\\t'"
facets_extra: --snp-count-orphans --gbuild mm10 --nbhd-snp 250
gunzip_extra: --to-stdout --decompress --force --verbose
sambamba:
  markdup: --remove-duplicates
tmb:
  min_coverage: 10
  allele_depth_keyname: "AD"
  tmb_highness_threshold: 10
params:
  center: GustaveRoussy
  ncbi_build: GRCm38
  chr:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - X
    - Y
    - MT
ref:
  cosmic:
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.all.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta
  gmt: null
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-associations_e98_r2020-05-03.tsv
  kaviar: null
  dbvar: null
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCm38.86
  capture_kit_bed: null
  af_only: null
  dbnsfp: null
  gnomad: null
  clinvar: null
  phastcons: null
  exac: null
gark_filters:
  DepthBelow60X: "DP < 59"
  VAFAbove10pct: "AF >= 0.1"
  GeneralPopulationBelow1pml: "dbNSFP_ExAC_Adj_AF >= 0.001"
  VAFAbove5pct: "AF >= 0.05"
  BelowQualByDepth: "QD <= 2.0"
  BelowBaseQuality: "QUAL < 30.0"
  AboveFisherStrandBias: "FS > 60.0"
  AboveStrandOddsRatio: "SOR > 3.0"
  BelowMappingQuality: "MQ < 35.0"
  BelowMQRankSum: "MQRankSum < -12.5"
  BelowReadPosRankSum: "ReadPosRankSum < -8.0"
samtools:
  fixmate_extra: -cmr
msisensor_pro:
  scan: -m 50
  msi: -f 0.05
threads: 20
fastq_screen:
  database:
    Contaminants:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters/Contaminants
    AThaliana:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis/Arabidopsis_thaliana.TAIR10
    Drosophila:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila/BDGP6
    Ecoli:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli/Ecoli
    Human:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human/Homo_sapiens.GRCh38
    Lambda:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda/Lambda
    Mitochondria:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria/mitochondria
    Mouse:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse/Mus_musculus.GRCm38
    PhiX:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX/phi_plus_SNPs
    Rat:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat/Rnor_6.0
    rRNA:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA/GRCm38_rRNA
    Vectors:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors/Vectors
    Worm:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm/Caenorhabditis_elegans.WBcel235
    Yeast:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast/Saccharomyces_cerevisiae.R64-1-1
    SalmoSalar:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/SalmoSalar/Salmo_salar.ICSASG_v2
  aligner_paths:
    bowtie2: bowtie2
