---
name: SigProfiler estimate
description: Estimate the optimum solution among different number of solutions.
authors:
  - Thibault Dayris
input:
  - signatures: Path to SigProfilerExtractor result directory
output:
  - csv: A csv file that contains the statistics of all solutions.
  - pdf: A plot that depict the Stability and Mean Sample Cosine Distance for different solutions.
params:
  - all_solution: Default is "All_Solutions". Path to a folder that contains the results of all solutions.
  - base_csvfile: Default is "All_solutions_stat.csv". Path to a csv file that contains the statistics of all solutions.
  - genomes: Default is Samples.txt. Path to a tab delimilted file that contains the mutation counts for all genomes given to different mutation types.
  - estimate_extra: Extra parameters for estimate_solution
notes: |
  notes
