---
name: deseq2_post_process
description: Post process DESeq2 results and create QC report.
authors:
  - Thibault Dayris
input:
  - DESeq2 results
output:
  - MultiQC report
  - Annotated result tables
