---
name: mixcr assemble partial
url: https://docs.milaboratories.com/mixcr/reference/mixcr-assemblePartial/
description: Overlaps alignments coming from the same molecule which partially cover CDR3 regions
authors:
  - Thibault Dayris
input:
  - Aligned sequences from `mixcr/align`
output:
  - report: txt alignment report
  - json: json alignment report
  - vdjca: collected alignment
params:
  - extra: Optional parameters