---
name: mane_to_vcftools_annotate
description: Use MANE summary to annotate a VCF with VCFtools
authors:
  - Thibault Dayris
input:
  - mane: Path to MANE summary
output:
  - mane: Path to the formatted mane.gz file
notes: |
  This is done to work with VCFtools only
