name: getfasta
description: bedtools getfasta extracts sequences from a FASTA file for each of the intervals defined in a BED/GFF/VCF file.
url: https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html
authors:
  - Thibault Dayris
input:
  - bed: Path to an interval file (BED/GFF/VCF)
  - ref: Path to a reference sequence (FASTA)
output:
  - Path to output file (BED/TSV/FASTA)
params:
  - extra: Optional parameters provided to `bedtools getfasta`
notes: |
  Output file type is automatically detected, no need to specify neither `-tab`, nor `-bedOut` options.
