---
name: extract_metadata
description: Extract a given metadata from a list of yaml files
authors:
  - Thibault Dayris
input:
  - One or multiple yaml files from iRODS/yaml
output:
  - A single TSV file with the requested meta data
notes: |
  Parameters:

  * Fields (list): A list of fields to keep
