---
name: GSEA NCG
description: Perform GSE analysis on Network of Cancer Genes
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the GSEA based on NCG
  - A TSV file containing the GSEA based on NCG
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Human only

  Parameters:
    * gseNCG_extra: Extra parameters for gseNCG, besides "gene", "readable", and "verbose"
