---
name: DOSE enrichment
description: Perform enrichment analysis on DOSE
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the enrichment based on DOSE
  - A TSV file containing the enrichment based on DOSE
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * enrichdo_extra: Extra parameters for enrichDO, besides "gene", "universe", and "readable"
    * organism: Either Hs or Mm
