---
name: EaCoN_CytoScan_process
description: Perform EaCoN CytoScan processing
authors:
  - Thibault Dayris
input:
  - Cytoscan CELL file
output:
  - Processing results as a RDS file
notes: |
  Use extra parameter to pass arguments to CS.Process. Default extra parameter
  is: `force=TRUE`

  The wildcard `sample` is required to identify sample name.
