---
name: EaCoN install
description: Download and install required database and optional scripts for EaCoN
authors:
  - Thibault Dayris
  - Bastien Job
input:
  - None
output:
  - Multiple packages/database
notes: |
  Parameters:

  * OncoScan: Install array specific libraries
  * OncoScanCNV: Install array specific libraries
  * CytoScan750K: Install array specific libraries
  * CytoScanHD: Install array specific libraries
  * norm: Install normalization methods (required for EaCoN)
  * EaCoN_dev: Install development version of EaCoN (overloads conda install)
  * EaCoN_chromosomes: Install EaCoN chromosome annotation
  * genomewide: Install genome wide information for WES and WGS
