design: design.tsv
fastp:
  fastp_extra: --verbose --trim_poly_g --trim_poly_x --average_qual 10 --overrepresentation_analysis --cut_front 5 --cut_tail 5 --cut_window_size 5
snpeff_snpsift:
  snpeff_extra: -noLog -nodownload -lof
  snpsift_kaviar: -name 'Kaviar_' -exists 'ExistsInKaviar' -tabix -noDownload -noLog
  snpsift_cosmic: -name 'cosmic_' -exists 'ExistsInCosmic' -tabix -noDownload -noLog
  snpsift_dbsnp: -name 'dbSNP_' -exists 'ExistsInDBsnp' -tabix -noDownload -noLog
  snpsift_clinvar: -name 'clinvar_' -exists 'ExistsInClinVar' -tabix -noDownload -noLog
  snpsift_gnomad: -name 'gnomad_' -exists 'ExistsInGnomAD' -tabix -noDownload -noLog
  snpsift_dbnsfp: -noDownload -noLog -f 'hg18_chr,hg18_pos(1-based)' -n -g hg38
  snpsift_gwascat: -g hg38 -noDownload -noLog
facets_extra: --snp-count-orphans --gbuild hg38 --nbhd-snp 250
gunzip_extra: --to-stdout --decompress --force --verbose
sambamba:
  markdup: --remove-duplicates --overflow-list-size 600000
tmb:
  min_coverage: 10
  allele_depth_keyname: "AD"
  tmb_highness_threshold: 10
gatk:
  gatk_filter_mutect_calls_extra: --create-output-variant-index --min-median-mapping-quality 35
  gatk_bcftools_split_multiallelic: "-m -both --check-ref w"
  apply_base_recal_extra: --create-output-bam-index
  gark_filters:
    DepthBelow60X: "DP < 59"
    VAFAbove10pct: "AF >= 0.1"
    GeneralPopulationBelow1pml: "dbNSFP_ExAC_Adj_AF >= 0.001"
    VAFAbove5pct: "AF >= 0.05"
    BelowQualByDepth: "QD <= 2.0"
    BelowBaseQuality: "QUAL < 30.0"
    AboveFisherStrandBias: "FS > 60.0"
    AboveStrandOddsRatio: "SOR > 3.0"
    BelowMappingQuality: "MQ < 35.0"
    BelowMQRankSum: "MQRankSum < -12.5"
    BelowReadPosRankSum: "ReadPosRankSum < -8.0"
samtools:
  fixmate_extra: -cmr
msisensor_pro:
  scan: -m 50
  msi: -f 0.05
params:
  center: GustaveRoussy
  ncbi_build: GRCh38
  chr:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - X
    - Y
    - MT
ref:
  cosmic: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.nochr.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-associations_e98_r2020-05-03.tsv
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/captureKitDesigns/hg38/v5/sureselect_v5.padded.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg38/somatic-hg38_af-only-gnomad.hg38.nochr.vcf.gz
  dbnsfp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz
  gnomad: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.bgz
  clinvar: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210404.vcf.gz
threads: 20
fastq_screen:
  database:
    Contaminants:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters/Contaminants
    AThaliana:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis/Arabidopsis_thaliana.TAIR10
    Drosophila:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila/BDGP6
    Ecoli:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli/Ecoli
    Human:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human/Homo_sapiens.GRCh38
    Lambda:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda/Lambda
    Mitochondria:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria/mitochondria
    Mouse:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse/Mus_musculus.GRCm38
    PhiX:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX/phi_plus_SNPs
    Rat:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat/Rnor_6.0
    rRNA:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA/GRCm38_rRNA
    Vectors:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors/Vectors
    Worm:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm/Caenorhabditis_elegans.WBcel235
    Yeast:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast/Saccharomyces_cerevisiae.R64-1-1
    SalmoSalar:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/SalmoSalar/Salmo_salar.ICSASG_v2
  aligner_paths:
    bowtie2: bowtie2
