---
name: Variant_Calling_Germline (under development)
description: Perform Variant calling on Germline
authors:
  - Thibault Dayris
  - M boyba Diop
  - Marc Deloger
input:
  - VCF files
  - Cosmic database formatted as gzipped vcf and its tbi index (already provided for IGR Flamingo users)
  - dbSNP database formatted as gzipped vcf and its tbi index (already provided for IGR Flamingo users)
  - MSigDB database formatted as GMT (already provided for IGR Flamingo users)
  - GWASCatalog database formatted as TSV (already provided for IGR Flamingo users)
  - Kaviar database formatted as gzipped vcf and its tbi index (already provided for IGR Flamingo users)
  - SnpEff database downloaded with SnpEff itself (already provided for IGR Flamingo users)
  - CaptureKit genomic intervals formatted as BED (already provided for IGR Flamingo users)
  - Known variants from dbSNP, with only AF within the INFO field for GATK (already provided for IGR Flamingo users)
  - dbNSFP database formatted as TSV (already provided for IGR Flamingo users)
  - FastQ Screen databases (already provided for IGR Flamingo users)
output:
  - Annotated VCF files
  - MultiQC report
usage:
  - \# Go to your working directory
  - cd /path/to/my/working/directory
  - \# Build a design file (see below)
  - \# Copy/paste the following line for **HG19**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/variant_calling_germline/run.sh
  - \# Copy/paste the following line for **HG38**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/variant_calling_germline/run.sh hg38
notes: |
  Prerequisites:

  * A TSV formatted design file, *named 'design.tsv'* with the following columns:

  .. list-table:: Desgin file format
    :widths: 33 33 33
    :header-rows: 1

    * - Sample_id
      - Upstream_fastq
      - Downstream_fastq
    * - Name of the Sample1
      - Path to upstream fastq file
      - Path to downstream fastq file
    * - Name of the Sample2
      - Path to upstream fastq file
      - Path to downstream fastq file
    * - ...
      - ...
      - ...
