---
name: Filter table
description: Filter your TSV file with pandas
authors:
  - Thibault Dayris
input:
  - A single TSV table
output:
  - A filtered TSV table
notes: |
  Parameters:

  * keep_column (List[str]): a list of column name to keep. Leave empty to keep all columns
  * keep_line (List[str]): a list of lines to keep. Leave empty to keep all lines
  * filters (List[Union[str, int, float]]): a list of filters to apply and the column to which apply this filter
  * drop_line (List[str]): a list of lines to drop. Leave empty to ignore.
  * drop_column (List[str]): a list of column name to drop. Leave empty to ignore.
  * drop_null_lines (bool): set to true to drop lines full of zeros.
  * drop_na_lines (bool): set to true to drop lines full of NAs.
  * dropna (bool): drop line with NA in any column.
  * drop_duplicated_lines (bool): search for duplicated lines and drop them. This is done AFTER all other filters.
  * new_index_col (str): set a column as first column in output table
