---
name: Filter table
description: Filter your TSV file with pandas
authors:
  - Thibault Dayris
input:
  - A single TSV table
output:
  - A filtered TSV table
notes: |
  Parameters:

  * keep_column (List[str]): a list of column name to keep. Leave empty to keep all columns
  * keep_line (List[str]): a list of lines to keep. Leave empty to keep all lines
  * filters (List[Union[str, int, float]]): a list of filters to apply and the column to which apply this filter
