---
name: compress_index_vcf
description: Compress and index VCF files
authors:
  - Thibault Dayris
input:
  - Uncompressed, unindexed VCF file
  - Optional genome index in order to add sequence information in the VCF (GATK compatibility)
output:
  - pbgzip Compressed, tabix indexed VCF file
notes: |
  The VCF file must be in directories, which tree is formatted as follows: {tool}/{subcommand}/{sample}.vcf
