---
name: vcftools annotate
description: Annotate VCF files with VCFtools
authors:
  - Thibault Dayris
input:
  - vcf: Path to vcf file that is to be annotated
  - annot: Path to annotation file (gzipped)
output:
  - vcf: Annotated VCF file
notes: |
  This wrapper requires at least two threads.
