---
name: sigprofiler_signatures
description: Compute mutational signatures with SigProfiler
authors:
  - Thibault Dayris
  - M boyba Diop
  - Marc Deloger
input:
  - (Annotated) VCF files (PBGZIP + TBI)
output:
  - Signatures per sample
  - Signature for complete cohort
usage:
  - \# Go to your working directory
  - cd /path/to/my/working/directory
  - \# Build a design file (see below)
  - \# Copy/paste the following line
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/sigprofiler_signatures/run.sh
notes: |
  Prerequisites:

  * A TSV formatted design file, *named 'design.tsv'* with the following columns:

  .. list-table:: Desgin file format
    :widths: 33 33 33
    :header-rows: 1

    * - Sample_id
      - Upstream_file
    * - Name of the Sample1
      - Path to upstream vcf file
    * - Name of the Sample2
      - Path to upstream vcf file
    * - ...
      - ...
