design: design.tsv
ref:
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
wisecondorx_extra:
  convert: "" # Do not use --reference
  newref: ""  # Do not use --cpus
  predict: "" # Do not use neither `--bed` nor `--plot`
  gender: ""
