design: design.tsv
ref:
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
wisecondorx:
  convert_extra: "" # Do not use --reference
  newref_extra: ""  # Do not use --cpus
  predict_extra: "" # Do not use neither `--bed` nor `--plot`
  gender_extra: ""
reads_nb: 
  - 1000000
seeds:
  - 42
  - 666
  - 123
bowtie2:
  build_extra: ""
  map_extra: "--sensitive-local"
