---
name: low_pass_wgs_copy_number
description: Analyse copy number variation with LowPass WGS using Bowtie2 and WisecondorX
authors:
  - Thibault Dayris
  - Marc Deloger
input:
  - A list of fastq files
output:
  - Copy number result
usage:
  - \# Go to your working directory
  - cd /path/to/my/working/directory
  - \# Build a design file (see below)
  - \# Copy/paste the following line for **HG19**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/low_pass_wgs_copy_number/run.sh hg19
  - \# Copy/paste the following line for **HG38**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/low_pass_wgs_copy_number/run.sh hg38
notes: |
  Prerequisites:

  * A TSV formatted design file, *named 'design.tsv'* with the following columns:

  .. list-table:: Desgin file format
    :widths: 33 33 33
    :header-rows: 1

    * - Sample_id
      - Upstream_fastq
      - Downstream_fastq
    * - Name of the Sample1
      - Path to upstream fastq file
      - Path to downstream fastq file
    * - Name of the Sample2
      - Path to upstream fastq file
      - Path to downstream fastq file
    * - ...
      - ...
      - ...
