---
name: occurence per chromosome
description: This wrapper performs the same analysis as the per-sample variant occurence, but works for a given chromosome.
authors:
  - Thibault Dayris
input:
  - calls: List of VCF formatted variant calling
output:
  - txt: Variant occurence for the given chromosome
notes: |
  Multiallelic sites *must* be splitted before this occurence analysis. They are
  treated as a single variant in this wrapper.
