---
name: msi_sensor_pro
description: Use MSISensor to call for MSI
authors:
  - Thibault Dayris
input:
  - fasta: Path to genome ffasta file
  - bed: Path to capture kit bed
  - bam: Path to pairs of tumor/normal bam files (with their indexes)
output:
  - MSI results
