---
name: msisensor_pro
description: Compute MSI scores with MSI sensor pro
authors:
  - Thibault Dayris
input:
  - fasta: Path to the genome fasta file
  - bed: Path to capture kit bed
  - Path to normal bam and its index
  - Path to tumoral bam and its index
output:
  - A list of MSI sensor files
params:
  - msi_pro_extra: Extra parameters for msi sensor pro (default none)
  - msi_scan_extra: Extra parameters for msi sensor scan (default none)
notes: |
  Key names are parameters passed through the configurarion dictionnary
