---
name: EaCoN Post Process
description: All EaCoN operations following the Oncoscan or Cytoscan Process
authors:
  - Thibault Dayris
  - Bastien Job
input:
  - Cytoscan or Oncoscan EaCoN RDS objects and directory architecture
output:
  - HTML report
  - CNV analysis
notes: |
  This meta wrapper is called through the EaCoN_OncoScan or the EaCoN_Cytoscan
  meta-wrappers

  Configuration architecture is duscissed in these meta-wrappers' pages.
