---
name: design_builder
description: Build design file from sample list
authors:
  - Thibault Dayris
input:
  - A list of samples, one per line, stored in a file called "samples.txt".
output:
  - A TSV-formatted design file with Sample_id, Upstream_file, Downstream_file
notes: |
  The samples must be in iRODS.

  Under development. Do no use.
