---
name: md5sum
description: Perform a MD5 hash and check it against optionally provided signature.
authors:
  - Thibault Dayris
input:
  - A file to hash
  - An optional hash result.
output:
  - A hash result
notes: |
  If a hash result is provided, then the md5sum result will be compared to the provided one, resulting in an error in case of any difference. Please keep in mind that file names **will not** be included in the hash comparison.
