design:
  path: design.tsv
pathways_of_interest: null
organism: Hs
gsea_extra:
  go: "pvalueCutoff = 1"
  do: "pvalueCutoff = 1"
  dgn: "pvalueCutoff = 1"
  ncg: "pvalueCutoff = 1"
  gsea: "pvalueCutoff = 1"
enricher_extra:
  go: "pvalueCutoff = 1, qvalueCutoff = 1"
  do: "pvalueCutoff = 1, qvalueCutoff = 1"
  dgn: "pvalueCutoff = 1, qvalueCutoff = 1"
  ncg: "pvalueCutoff = 1, qvalueCutoff = 1"
  enricher: "pvalueCutoff = 1, qvalueCutoff = 1"
barplot_extra: "color = 'p.adjust', showCategory = 8"
dotplot_extra: "showCategory = 10"
heatplot_extra: "showCategory = 10"
upsetplot_extra: "n = 8"
gmt:
  MSigDB_c1_Positional_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c1.all.v7.5.1.entrez.gmt
  MSigDB_c2_Curated_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.all.v7.5.1.entrez.gmt
  MSigDB_c3_Regulatory_Targets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.all.v7.5.1.entrez.gmt
  MSigDB_c4_Cancer_Oriented_MicroArray: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c4.all.v7.5.1.entrez.gmt
  MSigDB_c5_Onthology_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c5.all.v7.5.1.entrez.gmt
  MSigDB_c6_Oncogenic_Signatures: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c6.all.v7.5.1.entrez.gmt
  MSigDB_c7_Immunologic_Signatures: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c7.all.v7.5.1.entrez.gmt
  MSigDB_c8_Cell_Type_Signatures: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c8.all.v7.5.1.entrez.gmt
  MSigDB_hallmark: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/h.all.v7.5.1.entrez.gmt
  Chemical_genetic_perturbation: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cgp.v7.5.1.entrez.gmt
  Canonical_pathways: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cp.v7.5.1.entrez.gmt
  Biocarta: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cp.biocarta.v7.5.1.entrez.gmt
  KEGG: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cp.kegg.v7.5.1.entrez.gmt
  PID: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cp.pid.v7.5.1.entrez.gmt
  MSigDB_Reactome: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cp.reactome.v7.5.1.entrez.gmt
  MSigDB_WikiPathways: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c2.cp.wikipathways.v7.5.1.entrez.gmt
  MicroRNA_targets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.mir.v7.5.1.entrez.gmt
  miRDB: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.mir.mirdb.v7.5.1.entrez.gmt
  MicroRNA_legacy: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.mir.mir_legacy.v7.5.1.entrez.gmt
  Transcription_factor_targets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.tft.v7.5.1.entrez.gmt
  Transcription_factor_GTRD_Kolmykov: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.tft.gtrd.v7.5.1.entrez.gmt
  Transcription_factor_targets_legacy: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c3.tft.tft_legacy.v7.5.1.entrez.gmt
  Cancer_gene_neighborhood: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c4.cgn.v7.5.1.entrez.gmt
  Cancer_modules: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c4.cm.v7.5.1.entrez.gmt
  Gene_Othology_all: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c5.go.v7.5.1.entrez.gmt
  Gene_Othology_BP: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c5.go.bp.v7.5.1.entrez.gmt
  Gene_Othology_CC: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c5.go.cc.v7.5.1.entrez.gmt
  Gene_Othology_MF: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c5.go.mf.v7.5.1.entrez.gmt
  MSigDB_Human_Phenotype_Onthology: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c5.hpo.v7.5.1.entrez.gmt
  ImmuneSigDB: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c7.immunesigdb.v7.5.1.entrez.gmt
  Vaccine_Response: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/ENTREZID/7.5.1/c7.vax.v7.5.1.entrez.gmt
  WikiPathway: /mnt/beegfs/database/bioinfo/Index_DB/WikiPathway/HomoSapiens/hsapiens.WP.ENSG.gmt
  Reactome: /mnt/beegfs/database/bioinfo/Index_DB/Reactome/HomoSapiens/hsapiens.REAC.ENSG.gmt
  Human_Phenotype_Onthology: /mnt/beegfs/database/bioinfo/Index_DB/HumanPhenotypeOnthology/HomoSapiens/hsapiens.HP.ENSG.gmt
  Human_Protein_Atlas: /mnt/beegfs/database/bioinfo/Index_DB/HumanProteinAtlas/HomoSapiens/hsapiens.HPA.ENSG.gmt
  MiRNABase: /mnt/beegfs/database/bioinfo/Index_DB/MiRNABase/HomoSapiens/hsapiens.MIRNA.ENSG.gmt
  CORUM: /mnt/beegfs/database/bioinfo/Index_DB/CORUM/HomoSapiens/hsapiens.CORUM.ENSG.gmt
ppi:
  SMART: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/PPI_Protein_Domains__SMART_.tsv
  Pfam: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/PPI_Protein_Domains__Pfam_.tsv
  InterPro: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/PPI_Protein_Domains_and_Features__InterPro_.tsv
  Tissues: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/PPI_Tissue_expression__TISSUES_.tsv
  STRING: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/PPI_Local_Network_Cluster__STRING_.tsv
  Disease: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/PPI_Disease-gene_associations__DISEASES_.tsv
