design:
  path: design.tsv
pathways_of_interest: null
organism: Hs
gsea_extra:
  go: "pvalueCutoff = 1"
  do: "pvalueCutoff = 1"
  dgn: "pvalueCutoff = 1"
  msigdb: "pvalueCutoff = 1"
enricher_extra:
  go: "pvalueCutoff = 1, qvalueCutoff = 1"
  do: "pvalueCutoff = 1, qvalueCutoff = 1"
  dgn: "pvalueCutoff = 1, qvalueCutoff = 1"
barplot_extra: "color = 'p.adjust', showCategory = 8,"
dotplot_extra: "showCategory = 10"
heatplot_extra: "showCategory = 10"
upsetplot_extra: "n = 8"
