---
name: DESeq2_report
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge:pandoc=2.9.2.1
  - conda-forge:r-rmarkdown=2.1
  - conda-forge:r-dt=0.13
  - conda-forge:r-readr=1.3.1
  - conda-forge:r-dplyr=0.8.5
  - conda-forge:r-plyr=1.8.6
