---
name: Download Reference
description: Download sequence and annotations from Ensembl
authors:
  - Thibault Dayris
input:
  - None
output:
  - Fasta-formatted genome sequences (dna, cdna, and ncrna)
  - GTF-formatted genome annotation (complete)
  - VCF-formatted genome variations
notes: |
  Do not forget to cache these downloads!

  The samtools index step is here to include genome intervals in the VCF index. By doing so, the VCF is compatible with GATK for variant calling.
