channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::spliceai ==1.3.1
  - conda-forge::tensorflow ==2.6.0
  - conda-forge::tensorflow-gpu ==2.6.0
  - conda-forge::cudatoolkit ==11.5.0
