---
name: splice ai
description: Annotate VCF with Splice AI
authors:
  - Thibault Dayris
input:
  - vcf: Path to vcf that is to be annotated
  - fasta: Path to reference genome sequence (fasta formatted)
output:
  - vcf: Path to annotated VCF
params:
  - annotate: Genome version (following Gencode scheme)
