max_threads: 20

table_cols:
  - Chromosome
  - Start_Position
  - Variant_ID
  - SYMBOL
  - Reference_Allele
  - Tumor_Seq_Allele1
  - Mutect2_Read_depth
  - Tumor_Seq_Allele2
  - HGVSc
  - HGVSp
  - VarOcc
  - BIOTYPE
  - IMPACT
  - Variant_Classification
  - Mutect2_Read_depth
  - Mutect2_Allele_Frequency
  - Variant_Type
  - Tumor_Sample_Barcode
  - dbSNP_Pubmed
  - dbSNP_Clinical_Diagnostic_Assay
  - dbNSFP_ExAC_AlleleFrequency
  - Kaviar_Allele_Frequency
  - MSigDb_Pathways
  - dbNSFP_Polyphen2_HDIV_pred
  - dbNSFP_SIFT_pred
  - dbNSFP_FATHMM_pred
  - dbNSFP_ClinPred_score
  - dbNSFP_MutationTaster_pred
  - dbNSFP_MutationAssessor_pred
  - dbNSFP_MetaLR_pred
  - dbNSFP_LIST_S2_pred
  - dbNSFP_LRT_pred
  - dbNSFP_BayesDel_noAF_pred
  - dbNSFP_Aloft_pred
  - Transcript_ID
  - Gene
  - Feature
  - Filter
  - Center
  - Hugo_Symbol
  - End_Position

reference:
  ncbi_build: GRCh38
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  fasta_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta.fai
  fasta_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.dict
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/captureKitDesigns/hg38/v5/sureselect_v5.padded.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg38/somatic-hg38_af-only-gnomad.hg38.nochr.vcf.gz
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.nochr.vcf.gz
  dbsnp_tbi: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.nochr.vcf.gz.tbi
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz
  kaviar_tbi: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz.tbi
  cosmic: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz
  cosmic_tbi: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz.tbi
  dbnsfp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz
  clinvar: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210404.vcf.gz
  clinvar_tbi: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210404.vcf.gz.tbi
  gnomad: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.nochr.bgz
  gnomad_tbi: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.nochr.bgz.tbi
  exac: /mnt/beegfs/database/bioinfo/Index_DB/Exac/release1/ExAC.r1.sites.vep.fixed.vcf.gz
  exac_tbi: /mnt/beegfs/database/bioinfo/Index_DB/Exac/release1/ExAC.r1.sites.vep.fixed.vcf.gz.tbi
  dbvar: /mnt/beegfs/database/bioinfo/Index_DB/dbVar/GRCh38.variant_call.all.vcf.gz
  dbvar_tbi: /mnt/beegfs/database/bioinfo/Index_DB/dbVar/GRCh38.variant_call.all.vcf.gz.tbi
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  mane: /mnt/beegfs/database/bioinfo/Index_DB/MANE/MANE_human/release_0.95/MANE.GRCh38.v0.95.summary.txt.gz
  revel: /mnt/beegfs/database/bioinfo/Index_DB/REVEL/revel_with_transcript_ids
  mistic: /mnt/beegfs/database/bioinfo/Index_DB/MISTIC/MISTIC_GRCh38.tsv.gz
  cancer_census: /mnt/beegfs/database/bioinfo/Index_DB/CancerGeneCensus/Census_allTue_Aug_31_15_11_39_2021.csv
  oncokb: /mnt/beegfs/database/bioinfo/Index_DB/OncoKB/OncoKB.csv
  bwa_index: 
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.0123
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.amb
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.ann
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.bwt.2bit.64
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.pac
  msi_scan: /mnt/beegfs/database/bioinfo/Index_DB/GRCh38.99/GRCh38.99.msi.list
  chr:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - X
    - Y
    - MT


fastp:
  fastp_adapters: null
  fastp_extra: ""


samtools:
  fixmate_extra: -cmr
  view_filter: -h -q 5


sambamba:
  index_extra: ""
  sort_extra: ""
  markdup_extra: --remove-duplicates


picard:
  collect_multiple_metrics: ""


gatk:
  apply_base_recal: --create-output-bam-index
  base_recalibrator: ""
  mutect2_extra: --create-output-variant-index --max-reads-per-alignment-start 0 --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter --annotation AlleleFraction --annotation AllelePseudoDepth --annotation --annotation AS_BaseQualityRankSumTest --annotation AS_FisherStrand --annotation AS_InbreedingCoeff --annotation --annotation AS_MappingQualityRankSumTest --annotation AS_QualByDepth --annotation AS_ReadPosRankSumTest --annotation AS_RMSMappingQuality --annotation --annotation AS_StrandBiasMutectAnnotation --annotation AS_StrandOddsRatio --annotation AssemblyComplexity --annotation BaseQuality --annotation --annotation BaseQualityHistogram --annotation BaseQualityRankSumTest --annotation ChromosomeCounts --annotation ClippingRankSumTest --annotation --annotation CountNs --annotation Coverage --annotation DepthPerAlleleBySample --annotation DepthPerSampleHC --annotation ExcessHet --annotation --annotation FeaturizedReadSets --annotation FisherStrand --annotation FragmentDepthPerAlleleBySample --annotation FragmentLength --annotation --annotation GenotypeSummaries --annotation InbreedingCoeff --annotation LikelihoodRankSumTest --annotation MappingQuality --annotation --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation OrientationBiasReadCounts --annotation --annotation OriginalAlignment --annotation PossibleDeNovo --annotation QualByDepth --annotation ReadPosition --annotation ReadPosRankSumTest --annotation --annotation ReferenceBases --annotation RMSMappingQuality --annotation SampleList --annotation StrandBiasBySample --annotation StrandOddsRatio --annotation --annotation TandemRepeat --annotation UniqueAltReadCountPossible
  learn_read_orientation_model: ""
  get_pileup_summaries: ""
  calculate_contamination: ""
  filter_mutect_calls: --create-output-variant-index --min-median-mapping-quality 35
  gatk_filters:
    DepthBelow10X: "DP < 10"
    BelowQualByDepth: "QD <= 2.0"
    BelowBaseQuality: "QUAL < 30.0"
    AboveFisherStrandBias: "FS > 60.0"
    AboveStrandOddsRatio: "SOR > 3.0"
    BelowMappingQuality: "MQ < 35.0"
    BelowMQRankSum: "MQRankSum < -12.5"
    BelowReadPosRankSum: "ReadPosRankSum < -8.0"


bcftools:
  split_multiallelic: -m -both --check-ref w


snpeff:
  extra: -nodownload -noLog


snpsift:
  dbsnp: -name 'dbSNP_' -tabix -noDownload -noLog
  kaviar: -name 'Kaviar_' -tabix -noDownload -noLog
  cosmic: -name 'cosmic_' -tabix -noDownload -noLog
  dbnsfp: -noDownload -noLog -n -f 'hg18_chr,hg18_pos(1-based)'
  clinvar: -name 'clinvar_' -tabix -noDownload -noLog
  gnomad: -name 'gnomad_' -tabix -noDownload -noLog
  exac: -name 'gnomAD_exomes_' -tabix -noDownload -noLog
  dbvar: -name 'dbVar_' -tabix -noDownload -noLog
  extract_all_fields: -s ';' -e '.'


bigr_additionals:
  remove_non_conventional_chromosomes: true
  format_to_info: ""


vcftools:
  mane: --columns INFO/MANE_NCBI_GeneID,INFO/MANE_Ensembl_Gene,INFO/MANE_HGNC_ID,INFO/MANE_symbol,INFO/MANE_name,INFO/MANE_RefSeq_nuc,INFO/MANE_RefSeq_prot,INFO/MANE_Ensembl_nuc,INFO/MANE_Ensembl_prot,INFO/MANE_MANE_status,CHROM,FROM,TO,INFO/MANE_chr_strand
  revel: --columns CHROM,POS,-,REF,ALT,INFO/REVEL_aaref,INFO/REVEL_aaalt,INFO/REVEL,INFO/REVEL_Ensembl_transcriptid
  mistic: --columns CHROM,POS,REF,ALT,INFO/MISTIC_score,INFO/MISTIC_pred


cnv_facets:
  extra: --snp-count-orphans --gbuild hg38 --nbhd-snp 250


msisensor:
  extra: ""
  stability_threshold: 3.5


annot_sv:
  install_dir: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/annot_sv/source/AnnotSV/
  extra: -annotationMode both -snvIndelPASS 1 -tx ENSEMBL -SVinputInfo 0


tmb:
  min_coverage: 10
  tmb_highness_threshold: 10
  allele_depth_keyname: AD


fastq_screen:
  database:
    Contaminants:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters/Contaminants
    AThaliana:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis/Arabidopsis_thaliana.TAIR10
    Drosophila:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila/BDGP6
    Ecoli:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli/Ecoli
    Human:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human/Homo_sapiens.GRCh38
    Lambda:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda/Lambda
    Mitochondria:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria/mitochondria
    Mouse:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse/Mus_musculus.GRCm38
    PhiX:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX/phi_plus_SNPs
    Rat:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat/Rnor_6.0
    rRNA:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA/GRCm38_rRNA
    Vectors:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors/Vectors
    Worm:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm/Caenorhabditis_elegans.WBcel235
    Yeast:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast/Saccharomyces_cerevisiae.R64-1-1
    SalmoSalar:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/SalmoSalar/Salmo_salar.ICSASG_v2
  aligner_paths:
    bowtie2: bowtie2
