---
name: bcftools_query
description: Extracts fields from VCF or BCF files and outputs them in user-defined format. See `BCFtools documentation <https://www.htslib.org/doc/bcftools.html#query>`_.
authors:
  - Thibault Dayris
input:
  - Indexed gzipped VCF or BCF file
output:
  - Query result in expected format
notes: |
  If output is labelled "sample_list", then "-l" is sent to bcftools query and no other options are needed

  If output is labelled "bed", then "-f'%CHROM\t%POS0\t%END\t%ID\n'" will be set as extra paramerters and no options are needed.
