name: plotHeatmap
description: |
  Calculate scores per genome regions and prepare intermediate
  files for DeepTools
authors:
  - Thibault Dayris
input:
  - TSV formatted matrix file from DeepTools computeMatrix
output:
  - PNG/EPS/PDF/SVG formatted heatmap
  - Optional BED formatted regions
  - Optional TSV fromatted matrix
