---
name: DESeq2_clustermap_genes
description: Build a differentially-expressed-gene-based clustered heatmap
authors:
  - Thibault Dayris
input:
  - TSV formatted DESeq2 result table
output:
  - A PNG image
notes: |
  Parameters:

  * padj_threshold (float): The adjusted pvalue threshold
  * fc_threshold (float): The fold change threshold
