---
name: iRODS_Yaml
description: Turn iRODS text answers into yaml formatted files
authors:
  - Thibault Dayris
input:
  - A text raw output of iRODS
output:
  - A Yaml-formatted text file containing the verry same information
