---
name: bcftools_annotate
description: Annotate VCF files with VCF/BED using bcftools
authors:
  - Thibault Dayris
input:
  - call: The VCF to annotate
  - annotation: The BED/VCF/TSV to annotate with
output:
  - The annotated VCF file
notes: |
  Use `--columns` in extra to set field names
