---
name: mixcr export clones
description: export alignment results from a binary file (.clna, .clns) to a human-readable text file with `mixcr <https://mixcr.readthedocs.io/en/master/export.html#export>`_
authors:
  - Thibault Dayris
input:
  - Alignments in clns or clna format
output:
  - TSV-formetted text file
