---
name: heatplot_clusterprofiler
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-enrichplot=1.6.0
  - bioconda:bioconductor-clusterprofiler=3.14.0
  - conda-forge:r-cairo=1.5_12
