---
name: GO enrichment
description: Perform entichment analysis on Gene Ontology
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the enrichment based on GO
  - A TSV file containing the enrichment based on GO
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * gseDO_extra: Extra parameters for gseDO, besides "gene", "readable", and "verbose"
    * organism: Either Hs or Mm
