---
name: sort
description: Bash sort files
authors:
  - Thibault Dayris
input:
  - Path to the file that is to be sorted
output:
  - Path to the sorted file
params:
  - keys: List of keys parameters
notes: |
  tmpdir and threading are automatically passed as arguments
