---
name: analyzeSwitchConsequences
description: Predicting Switch Consequences
authors:
  - Thibault Dayris
input:
  - Switch list
output:
  - Switch list with consequences predicted
notes: |
  Parameters:

  * extra (str): Extra parameters for analyzeSwitchConsequences excepted 'switchAnalyzeRlist' and 'consequencesToAnalyze'
  * consequences (List(str)): List of consequences to search for: ['intron_retention','coding_potential','NMD_status','domains_identified','ORF_seq_similarity']
