---
name: Variant Position
description: Compute relative position to a gene start
authors:
  - Thibault Dayris
input:
  - A VCF file containing the variant to position
output:
  - A TSV-formatted text file
notes: |
  Parameters:

  * header (bool): Weather to print column names or not

  The output file contains the following columns:

  +--------------+-------------------------+
  | Columns name | Content                 |
  +==============+=========================+
  | Chromosome   | Chromosome Name         |
  +--------------+-------------------------+
  | GeneID       | Gene Identifier         |
  +--------------+-------------------------+
  | Position     | Variant position        |
  +--------------+-------------------------+
  | Ref          | Reference nucleotide    |
  +--------------+-------------------------+
  | Alt          | Alternative nucleotide  |
  +--------------+-------------------------+
