---
name: analyzeORF
description: Analyse opend reading frames on switch lists
authors:
  - Thibault Dayris
input:
  - Isoform Switch list
output:
  - Isoform switch list with annotated ORF
notes: |
  Parameters:
    * extra: Optional parameters passed to importIsoformExpression, besides "parentDir"
