---
name: sansa
description: Structural variant annotation with Sansa, from the Delly suite
authors:
  - Thibault Dayris
input:
  - vcf: Path to a VCF that is to be annotated (CNV/SNP/INDEL)
  - gtf: Path to a GTF/GFF to annotate with (gzipped GFT/GFF3)
  - db: Path to a VCF/BCF to annotate with (gzipped vcf, with tbi alongside)
output:
  - vcf: Path to the annotated VCF
  - contained: Optional path to list of overlapping genes (potentially long for CNV)
params:
  - extra: Extra parameters, like `--distance 0`
