---
name: importIsoformExpression
description: Import Salmon/Kallisto/RSEM/... in InsoformSwitchAnalyseR
authors:
  - Thibault Dayris
input:
  - A list of Salmon/Kallisto/RSEM/... quant results
output:
  - A RDS-formatted InsoformSwitchAnalyseR object
notes: |
  Parameters:
    * extra: Optional parameters passed to importIsoformExpression, besides "parentDir"
