channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - conda-forge::r-base ==4.1.0
  - conda-forge::r-devtools ==2.4.2
  - conda-forge::r-dbi ==1.1.1
  - conda-forge::r-rsqlite ==2.2.5
  - conda-forge::r-rmarkdown ==2.8
  - bioconda::r-eacon ==0.3.4_1
  - bioconda::bioconductor-bsgenome ==1.60.0
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg19 ==1.4.3
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg38 ==1.4.3
  - bioconda::bioconductor-bsgenome.hsapiens.1000genomes.hs37d5 ==0.99.1
  - bioconda::bioconductor-affxparser ==1.64.0
  - bioconda::bioconductor-biostrings ==2.60.0
  - bioconda::bioconductor-aroma.light ==3.22.0
  - bioconda::bioconductor-copynumber ==1.32.0
  - bioconda::bioconductor-genomicranges ==1.44.0
  - bioconda::bioconductor-rhdf5 ==2.36.0
  - bioconda::bioconductor-limma ==3.48.0
  - bioconda::r-sequenza ==3.0.0
  - bioconda::r-facets ==0.6.1
  - bioconda::ascat ==2.5.2
  - conda-forge::r-foreach ==1.5.1
  - conda-forge::r-dplyr ==1.0.6
