---
name: EaCoN ASCN
description: Perform allele specific copy number analysis with EaCoN
authors:
  - Thibault Dayris
input:
  - A processed EaCoN object as RDS
output:
  - ASCN models
notes: |
  use the "extra" parameter to fill optional arguments
