---
name: make_pon
description: Build Panel of Normal over a list of Fastq files
authors:
  - Thibault Dayris
input:
  - Fastq files
output:
  - PoN
usage:
  - cd /path/to/project
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/make_pon/run.sh
