---
name: maskfasta
description: bedtools maskfasta masks sequences in a FASTA file based on intervals defined in a feature file.
url: https://bedtools.readthedocs.io/en/latest/content/tools/maskfasta.html
authors:
  - Thibault Dayris
input:
  - fasta: Path to a genome sequence
  - bed: Path to the mask file
output:
  - Path to the masked fasta file
params:
  - extra: Optional parameters for bedtools maskfasta
