name: bedtools maskfasta
description: Mask sequences in a FASTA file based on intervals defined in a feature file.
url: https://bedtools.readthedocs.io/en/latest/content/tools/maskfasta.html
authors:
  - Thibault Dayris
input:
  - bed: Path to a BED-formatted intervals file.
  - fasta: Path to a Fasta-formatted sequence file.
output:
  - Path to masked sequence file.
params:
  - extra: Optional parameters passed to `bedtools maskfasta`.
