---
name: split vcf features
description: |
  A VCF may include multiple fatures in a single position. In surch cases, the
  `ANN` field in info contains information for each single feature. While running
  snpsifs extract fields, this leads to non-human readable outputs.

  This script solves this issue by duplicating lines and splitting annotation.
authors:
  - Thibault Dayris
input:
  - call: An unsplitted vcf
output:
  - call: A VCF with one annotation within the `ANN` INFO tag, per line.
params:
  - annotation_tag: Optional name of the annotation tag to split (default is `ANN=`)
notes: |
  No information is lost, it is moved.

  This wrapper takes non-gzipped VCF files
