---
name: split vcf features
description: |
  A VCF may include multiple fatures in a single position. In surch cases, the
  `ANN` field in info contains information for each single feature. While running
  snpsifs extract fields, this leads to non-human readable outputs.

  This script solves this issue by duplicating lines and splitting annotation.
authors:
  - Thibault Dayris
input:
  - An unsplitted vcf
output:
  - A VCF with one annotation within the `ANN` INFO tag, per line.
notes: |
  No information is lost, it is moved.
