channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-maftools==2.6.0
  - bioconda::bioconductor-bsgenome.mmusculus.ucsc.mm10==1.4.0
  - conda-forge::r-nmf==0.21.0
