---
name: Oncoplot
description: |
  Compute and plot an Oncoplot with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_
authors:
  - Thibault Dayris
input:
  - A RDS-formatted maftools object
output:
  - A PNG-formatted oncoplot
notes: |
  For input, use maftools/read_maf

  Use "oncoplot_extra" to provide parameters to `maftools::oncoplot`,
  and "png_extra" to provide extra parameters to `grDevices::png`.
