---
name: Somatic TMB
description: Compute Tumor Molecular Burden
authors:
  - Thibault Dayris
input:
  - bed: Path to capture kit bed
  - vcf: Path to VCF file
output:
  - TMB values as a TSV text file
