---
name: somatic_tmb
description: Compute tumor mutational burden within somatic samples
authors:
  - Thibault Dayris
input:
  - bed: Path to the genome size estimation from capture kit bed file
output:
  - A TMB text file, TSV formatted
params:
  - filter_in: List of values to keep from the vcf FILTER column (default all)
  - filter_out: List of values to filter out from the vcf FILTER column (default none)
  - min_coverage: Minimum allele depth coverage (default 10)
  - allele_depth_keyname: Name of the allele depth key in INFO field (default AD)
  - sample_list: List of samples to compute TMB over
  - tmb_highness_threshold: Detection threshold (default 10)
notes: |
  Key names are parameters passed through the configurarion dictionnary
