---
name: fastq_screen_indexer
description: Build indexes and congif file for FastQ Screen
authors:
  - Thibault Dayris
input:
  - None
output:
  - Bowtie2 indexed genomes ()
  - TSV formatted FastQ Screen config file
