---
name: read_maf
description: Read MAF files and load them in R with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_
authors:
  - Thibault Dayris
input:
  - A MAF-formatted file
  - An optional clinical data
output:
  - An optional RDS-formatted file,
  - An optional TSV-formatted summary
notes: |
  Use "extra" to provide parameters to maftools::read.maf
