---
name: Remove Patch version
description: Remove the patch version from Ensembl cdna fasta file
authors:
  - Thibault Dayris
input:
  - A (gzipped?) fasta-formatted cdna sequence
output:
  - A (gzipped?) fasta-formatted cdna sequence with no patch version
notes: |
  If the input is gzipped, then add one thread to the initial one for decompression.
  If the output is gzipped, then add one thread to the final one for decompression.

  +----------------------+-----------------------+---------+
  | Input                | Output                | Threads |
  +======================+=======================+=========+
  | Input not compressed | Output not compressed | 1       |
  +----------------------+-----------------------+---------+
  | Input compressed     | Output not compressed | 2       |
  +----------------------+-----------------------+---------+
  | Input not compressed | Output compressed     | 2       |
  +----------------------+-----------------------+---------+
  | Input compressed     | Output compressed     | 3       |
  +----------------------+-----------------------+---------+
