---
name: wisecondorx_convert
description: Convert aligned reads (bam/cram) to .npz
url: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#stage-1-convert-aligned-reads-bamcram-to-npz
authors:
  - Thibault Dayris
input:
  - aln: Path to bam/cram file
  - ref: Path to reference fasta file
output:
  - Path to npz file
params:
  - extra: Optional arguments besides `--reference`
