---
name: MAFtools
description: Plot various information about your samples and your cohort with MAFtools
authors:
  - Thibault Dayris
input:
  cond1: list of MAF files
  cond2: list of MAF files
output:
  - PNG formatted MAF summay
  - RDS formatted MAF objects
  - PNG formatted oncoplots
  - PNG formatted titv plots
  - PNG formatted forest plot
  - PNG formatted oncogenic pathways
params:
  genes: list of genes of interest to center plots around
notes: |
  No inclusion of clinical data possible yet.
