---
name: imeta_ls
description: Perform iRODS ils command
authors:
  - Thibault Dayris
input:
  - None
output:
  - A text formtted raw ils output.
notes: |
  Use iRODS/imeta to get a list of collections
  Use iRODS/yaml to parse the output file

  Parameters:

  * extra (str): Extra parameters for `ils`
  * collections (str): Path to a file containing the list of collections
