---
name: imeta_ls
description: Perform iRODS `imeta ls` command
authors:
  - Thibault Dayris
input:
  - Optional collection list, one collection per line
output:
  - A text formtted raw `imeta ls` output.
notes: |
  Use iRODS/imeta qu and iRODS/extract_collections to get a list of collections
  Use iRODS/yaml to parse the output file easily

  Parameters:

  * extra (str): Extra parameters for `imeta ls`
  * name (str): A list of collections to look for
