---
name: catplot
description: Build categorical histogram with Seaborn
authors:
  - Thibault Dayris
input:
  - A single TSV-formatted table
output:
  - A PNG catplog
notes: |
  Use extra parameters to fill optional arguments to seaborn.catplot
