---
name: plot MA
description: Perform a MA plot over DESeq2 results
authors:
  - Thibault Dayris
input:
  - A DESeq2 TSV formatted wald test result
output:
  - A PNG image of the MA plot
notes: |
  Parameters:

  * alpha_threshold: The padj threshold used to classify
