---
name: mashmap
description: MashMap implements a fast and approximate algorithm for computing local alignment boundaries between long DNA sequences.
authors:
  - Thibault Dayris
input:
  - query: Path to query fasta/fastq files
  - fasta: Path to reference sequence file
output:
  - Path to alignment file
params:
  - extra: Optional parameters for MashMap
