---
name: treeplot
description: Group terms paiwise and plot clusters
url: https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html
authors:
  - Thibault Dayris
input:
  - edo: Enrich analysis from clusterProfiler
output:
  - png: Path to the treeplot
  - pairs: Path to pairwise_termsim result (RDS formatted)
params:
  - extra_paiwise_termism: Extra parameters for pairwise_termsim function
  - extra_treeplot: Extra parameters for treeplot function
