max_threads: 20

ref:
  fasta: null
  bismark_index: null
  bismark_frequencies: null

bismark:
  mapping_extra: --fastq --bam --phred33-quals --ambiguous --unmapped --nucleotide_coverage
  extract: --gzip --comprehensive --bedGraph
  skip_optional_reports: false

fastp:
  fastp_adapters: null
  fastp_extra: ""

bismark:
  mapping_extra: --fastq --bam --phred33-quals --ambiguous --unmapped --nucleotide_coverage
  extract: --gzip --comprehensive --bedGraph
  skip_optional_reports: false