---
name: DESeq2_report
description: Build a result report for DESeq2
authors:
  - Thibault Dayris
input:
  - A TSV result from one of the wald test levels
output:
  - A HTML report that explains the content of DESeq2 results
notes: |
  Parameters:

  * alpha_threshold: The padj threshold used to filter DGE
  * fc_threshold: The fold change threshold used to filter DGE

  Input files:
  * gseapp_tsv: Path to the GSEApp TSV file from a DESeq2 file
  * volcano: Path to the volcano plot
  * pval_hist: Path to the pvalue histogram
  * maplot: Path to the MA-plot
  * coldata: Path to the experimental design TSV
  * pca: Path to the PCA plot
  * pca_scree: Path to the PCA loadings
  * distro_expr: Path to the distribution of expression values
