---
name: DESeq2_report
description: Build a result report for DESeq2
authors:
  - Thibault Dayris
input:
  - A TSV result from one of the wald test levels
output:
  - A HTML report that explains the content of DESeq2 results
notes: |
  Parameters:

  * alpha_threshold: The padj threshold used to classify
