---
name: EaCoN Oncoscan
description: Analyse CNV on OncoScanHD Arrays with EaCoN
authors:
  - Thibault Dayris
  - Bastien Job
input:
  - Oncoscan CEL file
output:
  - Complete EaCoN analysis
  - HTML report
notes: |
  notes
