---
name: split vcf multiallelic
description: Split multiallelic sites over multiple lines
authors:
  - Thibault Dayris
input:
  - vcf: A vcf file
output:
  - vcf: An vcf file with multiallelic sites splitted
notes: |
  All fields must be detailed in header
