---
name: generate decoy
description: Generate decoy genome/transcriptome for further use with Salmon.
authors:
  - Thibault Dayris
input:
  - Transcriptome (fasta formatted, may be gzipped)
  - Genome sequence (fasta formatted, may be gzipped)
output:
  - (gzipped) gentrome (fasta formatted)
  - decoy sequence names (txt formatted)
notes: |
  See `this tutorial <https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/>`_ for more information.
