name: bcftools merge
url: https://samtools.github.io/bcftools/bcftools.html#index
description: Merge vcf/bcf files with bcftools.
authors:
  - Patrik Smeds
intpu:
  - calls: List of paths to VCF/BCF files.
output:
  - Merged VCF/BCF file, must be the first element in the output file list.
params:
  - Optional parameters, must be the first and only value in snakemake's params.
notes: |
  * BCFTools will take longer to merge non-gzipped VCF files.
  * The `uncompressed_bcf` param allows to specify that a BCF output should be uncompressed (ignored otherwise).
  * The `extra` param allows for additional program arguments (not `--threads`, `-o/--output`, or `-O/--output-type`).
