---
name: read peak file hg19
description: Load Peak files in R with ChipSeeker for hg19
authors:
  - Thibault Dayris
input:
  - bed: A single peak file from macs2
output:
  - granges: A RDS formatted GRanges object containing peaks
  - tagmatrix: A RDS formatted TagMatrix object containing peaks
params:
  - extra_readpeaks: Optional parameters for ReadPeakFile function
  - extra_promoters: Optional parameters for getPromoters function
  - extra_tagmatrix: Optional parameters for getTagMatrix function
