name: sleuth_fit
description: |
  Fit a provided model to sleuth object
authors:
  - Thibault Dayris
input:
  - RDS formatted sleuth object
output:
  - RDS formatted sleuth object with fitted model
notes: |
  You can call this wrapper multiple times on the same sleuth object in order
  to fit multiple models (eg. full, reduced, ...), and then run sleuth_lrt.
