channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioinfokit=1.0.8
  - numpy=1.20.1
  - pandas=1.2.3
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - matplotlib-venn=0.11.6
  - adjusttext=0.7.3.1
  - imagemagick==7.0.11_4
  - fastcluster==1.1.26
