---
name: biskmark
description: A pipeline to map bisulfite converted sequence reads and determine cytosine methylation states
authors:
  - Thibault Dayris
input:
  - genome: Path to fasta formatted genome sequence
output:
  - indexes: biskmark genome indexes
