---
name: estimate Size Factors
authors:
  - Thibault Dayris
input:
  - A DESeq2 dataset object as RDS
output:
  - A DESeq2 dataset with estimated size factors
notes: |
  Any R parameters can be given to extra.
