name: bcftools norm
url: https://samtools.github.io/bcftools/bcftools.html#mpileup
description: Left-align and normalize indels, check if REF alleles match the reference, split multiallelic sites into multiple rows; recover multiallelics from multiple rows. For more information see `BCFtools documentation <https://www.htslib.org/doc/bcftools.html#norm>`_.
authors:
  - Dayne Filer
input:
  - call: Path to gzipped VCF or BCF, must be the first in the input file list
  - region: Optional region BED/GTF file
  - fasta: Required sequence file
output:
  - normalized VCF/BCF, must be the first output element
params:
  * Optional parameters, ust be the first and only value in snakemake's params.
  * The `uncompressed_bcf` param allows to specify that a BCF output should be uncompressed (ignored otherwise).
  * The `extra` param allows for additional program arguments (not `--threads`, `-f/--fasta-ref`, `-o/--output`, or `-O/--output-type`).
