---
name: mutation parser
description: Parse mutation spectrum from export aligment
authors:
  - Thibault Dayris
input:
  - An export of aligment from Mixcr
output:
  - A tsv containing the sequences and the observed mutations
note: |
  Return a four column file:

  *   Feature
  *   Position
  *   Reference
  *   Alternative
