---
name: enrichNCG
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-clusterprofiler=4.2.0
  - bioconda:bioconductor-org.hs.eg.db=3.14.0
  - bioconda:bioconductor-dose=3.20.0
