---
name: NCG enrichment
description: Perform enrichment analysis on Network of Cancer Gene
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the enrichment based on NCG
  - A TSV file containing the enrichment based on NCG
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * enrichNCG_extra: Extra parameters for enrichNCG, besides "gene", and "readable"
    * organism: Either Hs or Mm
