---
name: ConsensusClusterPlus
url: https://www.bioconductor.org/packages/release/bioc/html/ConsensusClusterPlus.html
description: Determe cluster number and class membership by stability evidence
authors:
  - Thibault Dayris
input:
  - counts: Expression matrix
output:
  - plot: Path to output graphs
params:
  - extra: Optional extra parameters
