---
name: trinucleotide Matrix mm9
description: Compute trinucleotide matrix with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_ on mm9
authors:
  - Thibault Dayris
input:
  - A RDS-formatted maftools object
output:
  - An optional RDS-formatted trinucleotide file
  - An optional PNG-formatted cophrenic correlation coefficient linegraph
notes: |
  Use "estimate_extra" to provide parameters to `maftools::estimateSignatures`,
  "trinuc_mat_extra", to provide extra parameters to `maftools::trinucleotideMatrix`,
  and "png_extra" to provide extra parameters to `grDevices::png`.
