---
name: variant occurence annotate
description: Annotate a VCF with a given occurence of variant
authors:
  - Thibault Dayris
input:
  - occurence: A TSV-formatted file counting occurence of a list of variants
  - calls: A list of VCF-formatted variants to annotate
output:
  - calls: List of annotated VCF in the exact same order as the input
notes: |
  Output VCF must be uncompressed
