---
name: DESeqDataSetFromTximport
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconductor-tximport==1.18.0
  - r-readr==1.4.0
  - r-jsonlite==1.7.2
  - bioconductor-deseq2==1.30.0
