channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-deseq2 ==1.32.0
  - conda-forge::r-readr ==1.4.0
  - conda-forge::r-jsonlite ==1.7.2
  - bioconda::bioconductor-tximport ==1.20.0
