---
name: DESeq DataSet From Tximport
authors:
  - Thibault Dayris
description: Import counts from Tximport into DESeq2
input:
  - A tximport RDS file
  - A TSV design file as described in DESeq2 documentation
output:
  - A RDS file of the DDS object.
notes: |
  Depending on your formula, your design file can contain any number of
  optional columns

  Parameters:

  * design: the R formulae used to performs differential expression
  * levels: a list of condition to study. The first one is the reference level
