---
name: split_design
description: split complex differential analysis design into simple ones
authors:
  - Thibault Dayris
input:
  - A TSV formatted table
output:
  - Multiple TSV formatted tables
notes: |
  This is done in order to satisfy both requests: (1) automatic DESeq2 statistical formulas building and (2) simplify readability of DESeq2 results
