---
name: split_design
description: split complex differential analysis design into simple ones
authors:
  - Thibault Dayris
input:
  - design: A TSV formatted table
output:
  - out_dir: Path to directory containing multiple TSV formatted tables
params:
  - read_csv: Optional arguments passed to `pandas.read_csv`,
  - columns_to_aggregate: List of columns to aggregate together
  - columns_to_remove: List of columns to drop
notes: |
  This is done in order to satisfy both requests: (1) automatic DESeq2 statistical formulas building and (2) simplify readability of DESeq2 results
