---
name: Variant Frequency
description: Compute relative position to a gene start
authors:
  - Thibault Dayris
input:
  - A TSV file containing the results of variant_distribution/position
  - A TSV file containing the results of gtf/gene_length
output:
  - A TSV-formatted text file
notes: |
  Parameters:

  * header (bool): Weather to print column names or not

  Warning:

  * Use `positions=True` in gtf/gene_length
  * Use `header=True` in both gtf/gene_length and variant_distribution/position

  The output file contains the following columns:

  +--------------------+------------------------------------------------------------+
  | Columns name       | Content                                                    |
  +====================+============================================================+
  | Chromosome         | Chromosome Name                                            |
  +--------------------+------------------------------------------------------------+
  | GeneID             | Gene Identifier                                            |
  +--------------------+------------------------------------------------------------+
  | GeneName           | The gene name                                              |
  +--------------------+------------------------------------------------------------+
  | Position           | Variant position                                           |
  +--------------------+------------------------------------------------------------+
  | Ref                | Reference nucleotide                                       |
  +--------------------+------------------------------------------------------------+
  | Alt                | Alternative nucleotide                                     |
  +--------------------+------------------------------------------------------------+
  | Start              | The gene start position                                    |
  +--------------------+------------------------------------------------------------+
  | Stop               | The gene stop position                                     |
  +--------------------+------------------------------------------------------------+
  | Relative           | The relative position of the variant in a gene             |
  +--------------------+------------------------------------------------------------+
  | RelativeFrequency  | Frequency of the relative position of a variant in a gene  |
  +--------------------+------------------------------------------------------------+
  | VariantFrequency   | The mutation frequency at this position                    |
  +--------------------+------------------------------------------------------------+
  | AltFrequency       | The frequency of this mutation at this position            |
  +--------------------+------------------------------------------------------------+
