---
name: extract somatic
description: Extrac somatic mutations from a VCF file
authors:
  - Thibault Dayris
input:
  - vcf: Path to a (pbgzipped) vcf file
output:
  - yaml: Path to the yaml containing number of mutations
params:
  - filter_in: Values to keep in from the VCF FILTER column
  - filter_out: Values to drop out from the VCF FILTER column
notes: |
  You may filter based on the value in "FILTER" column
