channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge::python ==3.10.2
  - conda-forge::pandas ==1.4.0
  - conda-forge::numpy ==1.22.1
  - conda-forge::seaborn ==0.11.2
  - conda-forge::matplotlib ==3.5.1
  - conda-forge::pillow ==8.4.0
  - conda-forge::sklearn-contrib-lightning ==0.6.0
  - conda-forge::pyqt ==5.12.3
  - conda-forge::imagemagick ==7.1.0_22
  - conda-forge::graphicsmagick ==1.3.37
  - conda-forge::py-opencv ==4.5.5
