---
name: GSEA plot
description: Perform GSEA-like plot
authors:
  - Thibault Dayris
input:
  - A RDS-formatted GSEA result
output:
  - A PNG image of running enrichment score on pre-ranked list
notes: |
  Use clusterProfiler's GSEA wrapper to produce a suitable GSEA object

  Parameters:
    * gseDGN_extra: Extra parameters for gseaplot2, besides "x"
