---
name: GSEA DNG
description: Perform GSE analysis on DNG database
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the GSEA based on DNG
  - A TSV file containing the GSEA based on DNG
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * gseDGN_extra: Extra parameters for gseDGN, besides "gene", "readable", and "verbose"
    * organism: Either Hs or Mm
