---
name: GSEA DOSE
description: Perform GSE analysis on DOSE
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the GSEA based on DOSE
  - A TSV file containing the GSEA based on DOSE
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * gseDO_extra: Extra parameters for gseDO, besides "gene", "readable", and "verbose"
    * organism: Either Hs or Mm
