---
name: vcf_post_process
description: Format gzipped VCF to TSV with renamed columns and human-friendly content when possible.
authors:
  - Thibault Dayris
input:
  - VCF formatted annotated calls
output:
  - TSV formatted calls (including MAFtools compatibility)
notes: |
  VCF header will be used to extract information, no need to list them all.
