---
name: Concatenate fastq
description: Contactenate fastq files
authors:
  - Thibault Dayris
input:
  - Multiple fastq files
output:
  - A single merged fastq file
notes: |
  This is a dummy port of gzip
