---
name: pathview
description: Perform pathway enrichment
authors:
  - Thibault Dayris
input:
  - A RDS-formatted gene list
output:
  - A PNG image of pathway enrichment
notes: |
  Use clusterProfiler's GeneList to produce the correct geneList object

  Parameters:
    * extra: Extra parameters for pathview, besides "gene.data"
