---
name: Co-Oncoplot
url: https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#952_Co-onco_plots
description: Plot co-oncoplot based on two cohorts
authors:
  - Thibault Dayris
input:
  - maf: List of two maf RDS-formatted files
output:
  - png: PNG formatted co-oncoplot plot
