---
name: gatk_bqsr
description: Compute and apply base recalibration on BAM files with GATK
authors:
  - Thibault Dayris
input:
  - Bam formatted mapped reads
output:
  - Bam formatted recalibrated reads
notes: |
  From: https://gatk.broadinstitute.org/hc/en-us/articles/360035890531-Base-Quality-Score-Recalibration-BQSR-

  > You should almost always perform recalibration on your sequencing data. In human data, given the exhaustive databases of variation we have available, almost all of the remaining mismatches -- even in cancer -- will be errors, so it's super easy to ascertain an accurate error model for your data, which is essential for downstream analysis. For non-human data it can be a little bit more work since you may need to bootstrap your own set of variants if there are no such resources already available for you organism, but it's worth it.

  Warning:

  * Bam files must have read groups
