---
name: dotplot_clusterprofiler
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-enrichplot=1.14.1
  - bioconda:bioconductor-clusterprofiler=4.2.0
  - conda-forge:r-cairo=1.5_12
