---
name: DGN enrichment
description: Perform enrichment analysis on DisGeNET
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the enrichment based on DisGeNET
  - A TSV file containing the enrichment based on DisGeNET
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * enrichdgn_extra: Extra parameters for enrichDGN, besides "gene", "universe", and "readable"
    * organism: Either Hs or Mm
