name: gatk CreateSomaticPanelOfNormals
description: |
  Run gatk CreateSomaticPanelOfNormals.
authors:
  - Thibault Dayris
input:
  - Genomics database
  - Reference fasta
output:
  - VCF formatted Somatic Panel of Normal.
notes: |
  * The `java_opts` param allows for additional arguments to be passed to the java compiler, e.g. "-Xmx4G" for one, and "-Xmx4G -XX:ParallelGCThreads=10" for two options.
  * The `extra` param allows for additional program arguments.
  * For more information see, https://gatk.broadinstitute.org/hc/en-us/articles/360036364532-CreateSomaticPanelOfNormals-BETA-
