---
name: DESeq2_post_process
description: Plot various information based on DESeq2 results
authors:
  - Thibault Dayris
input:
  - TSV-formatted DESeq2 results
  - TSV-formatted normalized counts
output:
  - A PNG formatted volcano plot
  - A PNG formatted sample-oriented clusterized heatmap
  - A PNG formatted gene-oriented clusterized heatmap
  - A PNG formatted MA plot
  - A PNG formatted PCA plot
  - A MultiQC html report
notes: |
  MultiQC report is based on configurations from in-house scripts.
