---
name: titv
description: Compute and plot Ti/Tv with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_
authors:
  - Thibault Dayris
input:
  - A MAF-formatted file
  - An optional clinical data
output:
  - An optional RDS-formatted file
  - An optional png-formatted titv plot
  - An optional TSV-formatted titv table
notes: |
  Use "titv_extra" to provide parameters to `maftools::titv`, "plottitv_extra",
  to provide extra parameters to `maftools::plotTiTv`, and "png_extra" to
  provide extra parameters to `grDevices::png`.
