---
name: meta_caller_germline
description: Gather calls from Mutect2 and Varscan2
authors:
  - Thibault Dayris
input:
  - VCF from Mutect2, and its tbi aside
  - VCF from Varscan2, and its tbi aside
output:
  - Merged, annotated VCF, with its tbi aside.
notes: |
  Input VCF files are supposed to be filtered and not annotated (merging annotations may lead to errors with BCFTools).
