---
name: analyzePFAM
description: Add PFAM analysis to switch list
authors:
  - Thibault Dayris
input:
  - Swtich list
  - PFAM results
output:
  - Switch list with PFAM results included
notes: |
  Parameters:
    * extra: Optional parameters passed to importIsoformExpression, besides "switchAnalyzeRlist" and "pathToPFAMresultFile"
