---
name: translate_vcf_seqoia
description: Translate VCF fields to fit Seqoia/GLeaves requirements
authors:
  - Thibault Dayris
input:
  - call: Path to BCF/VCF/VCF.GZ calls. Note that compressed calls requiers an additional thread.
output:
  - call: Path to translated calls. Note that compressed calls requiers an additional thread.
  - index: Optional path to tabix index.
