---
name: PCA
description: Build a PCA and plot-it with Bioinfokit and scikit-learn
authors:
  - Thibault Dayris
input:
  - Normalized counts of each sample
output:
  - PNG-formatted PCA
  - Optional PNG-formatted Scree-plot
