---
name: EaCoN_OncoScan_process
description: Perform EaCoN OncoScan processing
authors:
  - Thibault Dayris
input:
  - Oncoscan CELL file
output:
  - Processing results as a RDS file
notes: |
  Use extra parameter to pass arguments to OS.Process. Default extra parameter
  is: `force=TRUE`

  The wildcard `sample` is required to identify sample name.
