---
name: extractSequence
description: Extracting Nucleotide and Amino Acid Sequences
authors:
  - Thibault Dayris
input:
  - Switch list with isoforms tested
output:
  - Switch list with extracted sequences
notes: |
  Parameters:

  * extra (str): Extra parameters basides 'switchAnalyzeRlist'
