---
name: search_samples
description: Search for a list of samples in GR iRODS
authors:
  - Thibault Dayris
input:
  - Optional file containing a list of input sample names (one per line)
output:
  - TSV-formatted table with Sample_id, Upstream_file and Downstream_file
notes: |
  Input sample list may be provided through params: samples. As a list of strings.
