---
name: annot_sv
description: Annotate Facets VCF with AnnotSV
authors:
  - Thibault Dayris
input:
  - VCF files
output:
  - Annotated TSV files with Census data
usage:
  - \# Go to your working directory
  - cd /path/to/my/working/directory
  - \# Build a design file (see below)
  - \# Copy/paste the following line for **HG38**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/annotsv/run.sh
notes: |
  Prerequisites:

  * A TSV formatted design file, *named 'design.tsv'* with the following columns:

  .. list-table:: Desgin file format
    :widths: 33 33 33
    :header-rows: 1

    * - Sample_id
      - VCF_file
    * - Name of the Sample1
      - Path to Facets VCF file
    * - ...
      - ...
