---
name: SigProfiler Extractor
description: Extract signatures from VCF files with SigProfiler
authors:
  - Thibault Dayris
input:
  - ref: Path to reference TAR file
  - vcf: Path to input vcf (ignored if matrix is provided)
  - matrix: Path to input table (ingored if vcf is provided)
output:
  - signatures: Path to result dir
params:
  - ref: reference name
  - extractor_extra: Dict of extra parameters for SigProfilerExtractor
notes: |
  notes
