channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit ==11.5.0
  - pytorch ==1.10.0
  - pip ==21.3.1
  - pip:
    - SigProfilerMatrixGenerator
    - SigProfilerSimulator
    - SigProfilerExtractor
    - SigProfilerPlotting
