---
name: SigProfiler MatrixGenerator
description: Generate SBS, DBS, XBS matrices from VCF files
authors:
  - Thibault Dayris
input:
  - vcf: Path to input VCF files list
  - ref: Path to genome reference TAR archive
output:
  - matrices: Path to result dir
params:
  - project_name: Name of the project
  - matrix_extra: Dict of extra parameters to give to SigProfilerMatrixGeneratorFunc. Default `{"plot"=True, "exome"=False, "bed_file"=None, "chrom_based"=False, "tsb_stat"=False, "seqInfo"=False, "cushion"=100}`
notes: |
  Optional parameters are set to be the same as Tutorial
