---
name: coverage_variant_region
description: Compute coverage around variants and annotate VCF with this information.
authors:
  - Thibault Dayris
input:
  - vcf: The VCF files to annotate
  - bam: The corresponding bam files in matching order
  - gtf: The genome annotation in gtf format
  - bed: The capture-kit bed file
output:
  - vcf: The annotated VCF file
  - bedgraph: The genome coverage in bedgraph
  - sequencing_depth: Text file containing sequencing depth information
notes: |
  The "bin_size" parameter is used to get the window size to compute coverage around a given variant.
