---
name: somatic_signatures
description: Filter a VRange file and keep only SNVs
authors:
  - Thibault Dayris
input:
  - VCF files
output:
  - PNG image
notes: |
  This wrapper exists because SomaticSignatures only takes SNP into account
