---
name: preFilter
description: Filter isoform expression
authors:
  - Thibault Dayris
input:
  - A switch analyse list
output:
  - A filtered switch analyse list
notes: |
  Parameters:
    * extra: Extra parameters for function preFilter, besides "switchAnalyzeRlist"
