---
name: rename_snpsift_maf_cols
description: |
Columns from snpsift are usually named in a non-human readable manner.
authors:
  - Thibault Dayris
input:
  - tsv: TSV formatted calls
  - vcf: Optional VCF-formatted cols to write down columns significations
output:
  - tsv: TSV formatted calls, with renamed columns
  - txt: Text file with description of all columns content (if VCF was provided)
notes: |
  Further columns descriptions may be added.
