name: gatk GetPileupSummaries
description: |
  Run gatk GetPileupSummaries on the tumor BAM to summarize read support for a set number of known variant sites.
authors:
  - Thibault Dayris
input:
  - BAM formatted mapped reads
  - VCF formatted variants
output:
  - pileup summaries table
notes: |
  * The `java_opts` param allows for additional arguments to be passed to the java compiler, e.g. "-Xmx4G" for one, and "-Xmx4G -XX:ParallelGCThreads=10" for two options.
  * The `extra` param alllows for additional program arguments.
  * For more inforamtion see, https://software.broadinstitute.org/gatk/documentation/article?id=11050
