name: STAR-Fusion-Inspector
url: https://github.com/STAR-Fusion/STAR-Fusion/wiki
description: Align and search fusions with STAR, clean with FusionInspector, and annotate with FusionAnnotator
author:
  - Thibault Dayris
  