---
name: plotMutationSpectrum
description: Plot Mutational spectrum
authors:
  - authors
input:
  - A RDS-formatted mutational context
output:
  - PNG image of the mutational spectrum
notes: |
  This version is a not the original SomaticSignatures'. It plots more context.

  See VariantAnnotation, Rsamtools, and SomaticSignatures wrappers
  for input requirements.
