---
name: iRODS_quant_design
description: BUild quantification design for IGR Flamingo
authors:
  - Thibault Dayris
input:
  - A TSV ofrmatted list of file and their metadata. One file per line.
output:
  - A TSV formatted design file that suits rna-count-salmon pipeline
notes: |
  Parameters:

  * Column mapping (dict): Mentionned columns will be renamed.
  * Common_keys (list): A list of keys used to identify samples.
