---
name: SigProfiler GenInstall
description: Download and install references for SigProfiler
authors:
  - Thibault Dayris
output:
  - ref: Path to reference file
params:
  - ref: Optional reference name if no reference is provided in input.
notes: |
  notes
