# General pipeline options
minimum-trimmed-read-length: 8
mask-short-adapter-reads: 8
mask-short-adapter-reads: 8

# Select which parts of the pipeline should be run
steps:
  demux: TRUE 
  qc:   TRUE

# Path to design file (relative or absolute)
design: design.tsv


