channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge::r-dplyr ==1.0.7
  - conda-forge::r-ggplot2 ==3.3.4
  - conda-forge::r-tidyr ==1.1.3
  - conda-forge::r-tibble ==3.1.2
  - bioconda::r-immunedeconv ==2.0.3
  - conda-forge::r-readr ==1.4.0
  - conda-forge::r-rcolorbrewer ==1.1_2
  - conda-forge::r-randomcolor ==1.1.0
