---
name: translate_snpeff_maf_effect
description: Translate SnpEff effects in `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_ default effects (Warning: lossy translation)
authors:
  - Thibault Dayris
input:
  - A MAF-formatted file
output:
  - A MAF-formatted file, with effect column modified
note: |
  In order to prevent high reservations, multiple sed are used instead of a
  single, piped, long command line.
