---
name: plot_sigprofiler_single_sample
description: Plot signatures determined by SigProfiler Single Sample
authors:
  - Thibault Dayris
input:
  - sssig: Path to single sample sigprofiler result directory.
output:
  - hist: Path to sample signature histogram
notes: |
  Several files will be searched within the sssig directory. Do not move any file, do not rename any file.
