---
name: deseq
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-deseq2=1.26.0
  - bioconda:bioconductor-delayedarray=0.12.0
  - bioconda:bioconductor-summarizedexperiment=1.16.0
