channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-deseq2 ==1.34.0
  - bioconda::bioconductor-delayedarray ==0.20.0
  - bioconda::bioconductor-summarizedexperiment ==1.24.0
  - bioconda::bioconductor-biocparallel ==1.28.3
  - bioconda::bioconductor-apeglm ==1.16.0
  # - bioconda::bioconductor-ihw ==1.22.0
