channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-deseq2 ==1.32.0
  - bioconda::bioconductor-delayedarray ==0.18.0
  - bioconda::bioconductor-summarizedexperiment ==1.22.0
