---
name: DESeq
description: |
  Perform DESeq2 default analysis through size factor and dispersion estimates,
  and negative binomial GLM fitting and Wald test.
authors:
  - Thibault Dayris
input:
  - A DESeq2 Dataset
output:
  - A RDS object containing the DESeq2 Dataset with binomial Wald Test result
  - A TSV-formated text file for each level included in the DESeq2 Dataset
  - An optional normalized expression table
notes: |
  Parameters:
  * extra_deseq2  (str): Extra parameters for DESeq2::DESeq2 function, except `object`.
  * extra_results (str): Extra parameters for DESeq2::results function, except `object` and `name`.
  * factor: the factor used to call constrast. Necessary for "deseq2_tsv" only.
  * numerator: the numerator used to call constrast. Necessary for "deseq2_tsv" only.
  * denominator:  the denominator used to call constrast. Necessary for "deseq2_tsv" only.
