---
name: DESeq
description: |
  Perform DESeq2 default analysis through size factor and dispersion estimates,
  and negative binomial GLM fitting and Wald test.
authors:
  - Thibault Dayris
input:
  - A DESeq2 Dataset
output:
  - A RDS object containing the DESeq2 Dataset with binomial Wald Test result
  - A TSV-formated text file for each level included in the DESeq2 Dataset
notes: |
  Parameters:

  * alpha_threshold: The padj threshold used to filter the result table
  * fc_threshold: The fold change threshold used to filter the result table
