---
name: check MD5
description: Verify MD5 validity bewteen a provided file and a provided hash
authors:
  - Thibault Dayris
input:
  - A file to hash
  - An optional file that contains expected hash value
output:
  - A file containing both obtained and expected hash value and its correctness
notes: |
  If no expected-hash file is provided, then the hash value should be passed as
  a parameter: hash_value
