design: design.tsv
fastp:
  fastp_extra: ''
ref:
  cosmic: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.bgz
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86
  capture_kit_bed: /mnt/beegfs/userdata/t_dayris/hglft_www_2d6a7_9d3a70.bed
threads: 20
