design: design.tsv
snpeff_snpsift:
  snpeff_extra: -noLog -nodownload -lof
  snpsift_kaviar: -name 'Kaviar_' -exists 'ExistsInKaviar' -tabix -noDownload -noLog
  snpsift_cosmic: -name 'cosmic_' -exists 'ExistsInCosmic' -tabix -noDownload -noLog
  snpsift_dbsnp: -name 'dbSNP_' -exists 'ExistsInDBsnp' -tabix -noDownload -noLog
  snpsift_clinvar: -name 'clinvar_' -exists 'ExistsInClinVar' -tabix -noDownload -noLog
  snpsift_gnomad: -name 'gnomad_' -exists 'ExistsInGnomAD' -tabix -noDownload -noLog
  snpsift_dbnsfp: -noDownload -noLog -f 'hg18_chr,hg18_pos(1-based)' -n -g mm10
  snpsift_gwascat: -g mm10 -noDownload -noLog
params:
  center: GustaveRoussy
  ncbi_build: GRCm38
  chr:
    - chr1
    - chr2
    - chr3
    - chr4
    - chr5
    - chr6
    - chr7
    - chr8
    - chr9
    - chr10
    - chr11
    - chr12
    - chr13
    - chr14
    - chr15
    - chr16
    - chr17
    - chr18
    - chr19
    - chr20
    - chrX
    - chrY
    - chrMT
ref:
  cosmic:
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.all.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta
  gmt: null
  gwascat: null
  kaviar: null
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCm38.86
  capture_kit_bed: null
  af_only: null
  dbnsfp: null
  gnomad: null
  clinvar: null
  oncokb: null
  cancer_census: null
threads: 20
