design: design.tsv
snpeff_snpsift:
  snpeff_extra: -noLog -nodownload -lof
  snpsift_kaviar: -name 'Kaviar_' -exists 'ExistsInKaviar' -tabix -noDownload -noLog
  snpsift_cosmic: -name 'cosmic_' -exists 'ExistsInCosmic' -tabix -noDownload -noLog
  snpsift_dbsnp: -name 'dbSNP_' -exists 'ExistsInDBsnp' -tabix -noDownload -noLog
  snpsift_clinvar: -name 'clinvar_' -exists 'ExistsInClinVar' -tabix -noDownload -noLog
  snpsift_gnomad: -name 'gnomad_' -exists 'ExistsInGnomAD' -tabix -noDownload -noLog
  snpsift_dbnsfp: -noDownload -noLog -f 'hg18_chr,hg18_pos(1-based)' -n  -g hg19
  snpsift_gwascat: -g hg19 -noDownload -noLog
params:
  center: GustaveRoussy
  ncbi_build: GRCh37
  chr:
    - chr1
    - chr2
    - chr3
    - chr4
    - chr5
    - chr6
    - chr7
    - chr8
    - chr9
    - chr10
    - chr11
    - chr12
    - chr13
    - chr14
    - chr15
    - chr16
    - chr17
    - chr18
    - chr19
    - chr20
    - chr21
    - chr22
    - chrX
    - chrY
    - chrMT
ref:
  cosmic: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.vcf
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/hg19/144_20150605/All_20150605.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh37.75/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG19/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg19-trim.vcf.gz
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh37.75/
  capture_kit_bed: /mnt/beegfs/userdata/t_dayris/hglft_www_2d6a7_9d3a70.bed
  oncokb: /mnt/beegfs/database/bioinfo/Index_DB/OncoKB/OncoKB.csv
  cancer_census: /mnt/beegfs/database/bioinfo/Index_DB/CancerGeneCensus/Census_allTue_Aug_31_15_11_39_2021.csv
  mane: /mnt/beegfs/database/bioinfo/Index_DB/MANE/MANE_human/release_0.95/MANE.GRCh38.v0.95.summary.txt.gz
  revel: /mnt/beegfs/database/bioinfo/Index_DB/REVEL/revel_with_transcript_ids_and_chr
  mistic: /mnt/beegfs/database/bioinfo/Index_DB/MISTIC/MISTIC_GRCh37.chr.tsv.gz
threads: 20
