---
name: SnpEff_SnpSift
description: Annotate VCF with SnpEff and SNpSift
authors:
  - Thibault Dayris
input:
  - VCF files
output:
  - Annotated VCF file
usage:
  - \# Go to your directory containing VCF files
  - cd /path/to/CEL/dir
  - \# Copy/paster the following line
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/snpeff_snpsift/run.sh
