# General pipeline options
max_threads: 20


# Path to design file (relative or absolute)
design: design.tsv


# A short list of genes of interest
# Dedicated plots will be performed on these genes
genes_of_interest:
  - ENSG00000141510


# Fastp parameters
fastp:
  adapters: none
  fastp_extra: --cut_front --cut_tail --cut_window_size 6 --cut_mean_quality 10 --unqualified_percent_limit 50 --n_base_limit 7 --average_qual 0 --length_required 15 --overrepresentation_analysis


# Salmon parameters
salmon:
  index: /mnt/beegfs/database/bioinfo/Index_DB/Salmon/hg38/index
  salmon_libtype: A
  salmon_quant_extra: --numBootstraps 100 --gcBias --seqBias --posBias


# DESeq2 parameters
deseq2:
  design:
    columns_to_aggregate: null
    columns_to_ignore: null
    include_only: null
  tximport_extra: type='salmon', ignoreTxVersion=TRUE, ignoreAfterBar=TRUE
  thresholds:
    alpha: 0.05
    fc: 0.6

# Multiqc parameters
multiqc:
  title: Differential Gene Expression
  report_comment: This report has been made at Gustave Roussy
  email: bigr@gustaveroussy.fr
  application_type: RNA-Seq
  project_type: Application


# Rust-Bio-Tools
rbt:
  csv_extra: '--separator "\\t" --sort-column stat_change --sort-order ascending --rows-per-page 50'
  zip_extra: --create --version --bzip2 --file

# Star patameters
star:
  index: /mnt/beegfs/database/bioinfo/Index_DB/STAR/GRCh38
  chimera_extra: --outReadsUnmapped None --twopassMode Basic --outSAMstrandField intronMotif --outSAMunmapped Within --chimSegmentMin 12 --chimJunctionOverhangMin 8 --chimOutJunctionFormat 1 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --alignSJstitchMismatchNmax 5 -1 5 5 --outSAMattrRGline ID:GRPundef --outSAMattributes All --chimMultimapScoreRange 3 --chimScoreJunctionNonGTAG -4 --chimMultimapNmax 20 --chimNonchimScoreDropMin 10 --peOverlapNbasesMin 12 --peOverlapMMp 0.1 --alignInsertionFlush Right --alignSplicedMateMapLminOverLmate 0 --alignSplicedMateMapLmin 30
  variant_extra: --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMattributes All --twopassMode Basic


# Samtools extra parameters
# Be careful with parameters, do not break compatibility
samtools:
  index_extra: ""
  cram_extra: ""


# Star-fusion parameters and database
star_fusion:
  CTAT_resource_lib: /mnt/beegfs/database/bioinfo/Index_DB/CTAT_Resource_Lib/GRCh38_gencode_v37/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play.tar.gz
  extra: --FusionInspector inspect


# Arriba fusion detection
arriba:
  extra: ""


# GATK parameters
gatk:
  baserecalibrator: ""
  applybqsr: ""
  mutect2_extra: --max-reads-per-alignment-start 0 --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter
  pileup_summaries: ""
  calculate_contamination: ""
  learn_read_orientation_model: ""


# Fastq screen parameters
# Add new genomes below
fastq_screen:
  fastq_screen_config:
    database:
      Contaminants:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters/Contaminants
      AThaliana:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis/Arabidopsis_thaliana.TAIR10
      Drosophila:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila/BDGP6
      Ecoli:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli/Ecoli
      Human:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human/Homo_sapiens.GRCh38
      Lambda:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda/Lambda
      Mitochondria:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria/mitochondria
      Mouse:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse/Mus_musculus.GRCm38
      PhiX:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX/phi_plus_SNPs
      Rat:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat/Rnor_6.0
      rRNA:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA/GRCm38_rRNA
      Vectors:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors/Vectors
      Worm:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm/Caenorhabditis_elegans.WBcel235
      Yeast:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast/Saccharomyces_cerevisiae.R64-1-1
    aligner_paths:
      bowtie2: bowtie2
  subset: 100000
  aligner: bowtie2


# Immunedeconv parameters
# Add new tools below
immunedeconv:
  cibersort_binary: "/mnt/beegfs/software/cibersort/1.0.6/CIBERSORT.R"
  cibersort_mat: "/mnt/beegfs/software/cibersort/1.0.6/LM22.txt"
  tool_list: 
    - xcell
    - quantiseq
    - epic
    - mcpcounter
    - cibersort
    - cibersort_abs

  
# Genome information
# If you change genome data, please re-build all indexes.
reference:
  gtf: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.gtf
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  genome_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.dict
  genome_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta.fai
  refflat: /mnt/beegfs/database/bioinfo/Index_DB/refFlat/GRCm38/refFlat.txt.gz
  dbsnp: null
  dbsnp_tbi: null
  capturekit_bed: null
  chromosomes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - X
    - Y
    - MT