---
name: Signatures
description: |
  Extrat given signature from a trinucleotide matrix,
  compare them and plot cosine similarities with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_
authors:
  - Thibault Dayris
input:
  - A RDS-formatted trinucleotide matrix file
output:
  - An optional RDS-formatted compared signature
  - An optional TSV-formatted compared signature
  - An optional PNG-formatted cosine similarity heatmap
notes: |
  For input, see maftools/signatures

  Use "compare_extra" to provide parameters to `maftools::compareSignatures`,
  and "png_extra" to provide extra parameters to `grDevices::png`.
