---
name: DESeq2 Merge
description: Merge counts and results into a single TSV table
authors:
  - Thibault Dayris
input:
  - A TSV formatted text file containing the DESeq2 wald tests results
  - A TSV formatted text file containing the normalized counts
output:
  - A TSV file containing both informations
  - An optional filtered counts file based on a provided alpha and fold change threshold
  - An optional filtered deseq2 results based on a provided alpha and fold change threshold
notes: |
  THe first column is set as column index

  Parameters:

  * alpha: The alpha threshold (float)
  * fold_change: The fold change threshold (float)
