---
name: EaCoN_download_databases
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge:python=3.8.5
  - conda-forge:libcurl=7.71.1
  - conda-forge:webdavclient2=0.1.1
  - conda-forge:pip=20.2.3
  - pip:
      - webdavclient
