channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-txdb.hsapiens.ucsc.hg38.knowngene ==3.13.0
  - bioconda::bioconductor-chipseeker ==1.28.3
  - bioconda::bioconductor-org.hs.eg.db ==3.13.0
