restart-times: 2
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 2
jobs: 300
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.moose.snakejob.sh"
conda-prefix: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/conda
# singularity-prefix: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/singularity
wrapper-prefix: file:///mnt/beegfs/pipelines/snakemake-wrappers/
# use-singularity: true
use-conda: true
shadow-prefix: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/shadowed
