---
name: GMT gene set enrichment
description: Perform GSEA analysis on a given GMT file
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
  - A GMT file
output:
  - A RDS object containing the GSEA
  - A TSV file containing the GSEA
notes: |
  The geneList object if described in the
  hg38_genelist wrapper

  Parameters:
    * extra: Extra parameters for GSEA, besides `gene` and `TERM2GENE`
