---
name: compute tmb
description: Compute Tumor Mutational Burden
authors:
  - Thibault Dayris
input:
  - igs: Path to iterrogated genome sequence size (yaml)
  - samples: Path to a list of yaml files, one per sample
output:
  - tsv: Path to the result table
notes: |
  Compute Tumor Mutation Burden given the definition of
  Cancer Discov. 2020 Dec; 10(12): 1808–1825.
  Published online 2020 Nov 2. doi: 10.1158/2159-8290.CD-20-0522

  Tumor Mutational Burden (TMB) as a Predictive Biomarker in
  Solid Tumors
