name: "salmon"
description: Pseudo map and quantify your reads over transcritome with `Salmon <https://salmon.readthedocs.io/en/latest/>`_
authors:
  - Thibault Dayris
input:
  - Fasta formatted transcriptome sequence
  - Optional Fasta formatted genome sequence
  - Optional GTF file
  - Fastq formatted reads
Output:
  - Quantified reads over the provided reference
