---
name: mutect2_germline
description: Call variants on BAM files with Mutect2, considering a single bam file.
authors:
  - Thibault Dayris
input:
  - Bam formatted mapped reads
output:
  - VCF formatted raw variants from Mutect2
notes: |
  Bam are expected to be mate-fixed (see bwa_fixmate meta-wrapper).
