---
name: rest post
description: Send rest requests and get result in a json file
url: https://bedtools.readthedocs.io/en/latest/content/tools/maskfasta.html
authors:
  - Thibault Dayris
input:
  - fasta: Path to a genome sequence
  - bed: Path to the mask file
output:
  - Path to the masked fasta file
params:
  - extra: Optional parameters for bedtools maskfasta
