---
name: bcl2fastq
description: Demultiplex BCL files into Gzipped Fastq.
authors:
  - Thibault Dayris
  - M boyba Diop
  - Marc Deloger
  - Gérôme Jules-Clément
  - Marie Martelat
input:
  - BCL files
  - Sample sheet
output:
  - Fastq files
notes: |
  notes
