name: gatk LearnReadOrientationModel
description: |
  Run gatk LearnReadOrientationModel to estimate orientation bias
authors:
  - Thibault Dayris
input:
  - f1r2 tar.gz formatted archive
output:
  - GATK artifact model
notes: |
  * The `java_opts` param allows for additional arguments to be passed to the java compiler, e.g. "-Xmx4G" for one, and "-Xmx4G -XX:ParallelGCThreads=10" for two options.
  * The `extra` param alllows for additional program arguments.
  * For more inforamtion see, https://software.broadinstitute.org/gatk/documentation/article?id=11050
