---
name: varscan2_calling
description: Call variants on BAM files with Varscan2
authors:
  - Thibault Dayris
input:
  - Bam formatted mapped reads
output:
  - VCF formatted raw variants from Varscan2
notes: |
  Bam are expected to be mate-fixed, and recalibrated.
