---
name: imeta_qu
description: Perform imeta requests
authors:
  - Thibault Dayris
input:
  - None
output:
  - A text file containing imeta result
notes: |
  Parameters:

  * kwords (dict): A dictionary containing {key: value}. Replace "*" by "%" for glob and pattern research
  * extra (str): extra parameters for `imeta qu`
