---
name: mixcr assemble
description: Build clonotypes from alignments obtained with `mixcr <https://mixcr.readthedocs.io/en/master/assemble.html>`_.
authors:
  - Thibault Dayris
input:
  - Aligned sequences from mixcr
output:
  - Clonotypes
notes: |
  It is strongly encouraged to name your output file: *.clna when the `-a/--write-alignments` is used, and *.clns otherwise.
