---
name: EaCoN_Cytoscan
description: Analyse Cytoscans with EaCoN on Flamingo
authors:
  - Thibault Dayris
  - Bastien Job
  - Gérôme Jules-Clément
input:
  - CEL files
output:
  - Complete EaCoN anaysis directory
  - HTML report
usage:
  - \# Go to your directory containing CEL files
  - cd /path/to/CEL/dir
  - \# Copy/paster the following line
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/cytoscan_eacon/run.sh
