---
name: GeneLength
description: Get gene lengths from a GTF
authors:
  - Thibault Dayris
input:
  - A GTF formatted genome annotation
output:
  - A TSV formatted text file
notes: |
  Parameters:

  * header (bool) : Weather to write column header or not
  * positions (bool) : Weather to write positions or not
  * gencode (bool): Remove patch in ensembl identifiers

  The output file contains:

  +--------+----------+---------+------------+----------+----------+
  | GeneID | GeneName | Length  | Chromosome | Start    | Stop     |
  +========+==========+=========+============+==========+==========+
  | Awlays | Always   | Always  | Optional   | Optional | Optional |
  +--------+----------+---------+------------+----------+----------+
