---
name: EaCoN_Annotate
description: Annotate your segments with EaCoN
authors:
  - Thibault Dayris
input:
  - A RDS file
  - A GRD script
  - A set of databases
output:
  - Multiple PNG and text files.
  - HTML report
