---
name: EaCoN_Annotate
description: Annotate your segments with EaCoN
authors:
  - Thibault Dayris
input:
  - A RDS file
  - A GRD script
  - A set of databases
output:
  - A RDS file
notes: |
  Use extra parameters to st optional arguments

  Warning: This is very deeply linked to Gustave Roussy institute internal usage. GRD is not maintained and not easily share-able.
