---
name: wisecondorx
description: Search CNV in low pass WGS with WisecondorX
authors:
  - Thibault Dayris
input:
  - Unfiltered BAM files mapped with Bowtie2.
output:
  - Multiple tables and graphs from WisecondorX
