---
name: GMT enrichment
description: Perform over representation analysis on a given GMT file
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
  - A GMT file
output:
  - A RDS object containing the ORA
  - A TSV file containing the ORA
notes: |
  The geneList object if described in the
  hg38_genelist wrapper

  Parameters:
    * extra: Extra parameters for enricher, besides `gene` and `TERM2GENE`
