---
name: Seaborn Categorical Swarmplot
description: Build a Categorical Swarmplot over categorical data
authors:
  - Thibault Dayris
input:
  - A list of TSV-formatted dataframes
output:
  - A PNG-formatted image of the categorical swarmplot
notes: |
  Parameters:

  * column: the name of the column to plot
