---
name: igs estimation
description: Estimate the size of the interrogated genomic sequence.
authors:
  - Thibault Dayris
input:
  - bed: Path to a bed file
output:
  - json: Path to results (json formatted)
notes: |
  TMB is defined as the number of somatic mutations per megabase of interrogated genomic sequence.
