---
name: varscan2_somatic
description: Call variants on BAM files with Varscan2, considering a normal background and a tumor state.
authors:
  - Thibault Dayris
input:
  - Bam formatted mapped reads (tumor and normal)
output:
  - VCF formatted raw variants from Varscan2
notes: |
  Bam are expected to be mate-fixed (see bwa_fixmate meta-wrapper), and recalibrated (see gatk_bqsr meta-wrapper).
