---
name: CTC_Variant_Calling_Integragen_Legacy
description: Perform analyses alike mat&met available in Integragen reports
authors:
  - Thibault Dayris
input:
  - BAM files
output:
  - Called variants
usage:
  - Do not run
