---
name: retrotransposons
description: Quantify and search differentially expressed retrotransposons from RNASeq
authors:
  - Thibault Dayris
input:
  - Pairs of fastq files
output:
  - DESeq2 results
notes: |
  This is a variation of the initial RNASeq differential expression pipeline
