---
name: Clustermap
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge:python=3.8.2
  - conda-forge:pandas=1.0.1
  - conda-forge:numpy=1.18.1
  - conda-forge:seaborn=0.10.0
  - conda-forge:matplotlib=3.1.3
  - conda-forge:pillow=7.0.0
  - conda-forge:zlib=1.2.11
  - conda-forge:qt=5.12.5
  - conda-forge:pyqt=5.12.3
  - conda-forge:libxcb=1.13
  - conda-forge:xorg-libxcb=1.12
  - conda-forge:xorg-libxinerama=1.1.4
