---
name: Clustermap
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge:python=3.9.6
  - conda-forge:pandas=1.3.1
  - conda-forge:numpy=1.21.1
  - conda-forge:matplotlib=3.4.2
  - conda-forge:pillow=8.3.1
  - conda-forge:zlib=1.2.11
  - conda-forge:pyqt=5.12.3
  - conda-forge:libxcb=1.13
  - conda-forge:xorg-libxcb=1.12
  - conda-forge:xorg-libxinerama=1.1.4
  - conda-forge:seaborn=0.11.1
  - onda-forge:fastcluster ==1.1.26
