---
name: Seaborn Clustermap Genes
description: Build a clustered heatmap on differentially expressed genes
authors:
  - Thibault Dayris
input:
  - A TSV-formatted TPM counts of differentially expressed genes
output:
  - A PNG-formatted image of the clustered heatmap
notes: |
  Parameters:

  * row_cluster: Perform clustering on rows
  * col_cluster: Perform clustering on columns
  * row_condition_color: Set colors on rows according to condition array
  * robust: Use robust quantiles instead of the extreme values
  * ylabel_rotation: The X label rotation
  * xlabel_rotation: The Y label rotation
