---
name: EaCoN Cytoscan
description: Analyse CNV on CytoScanHD Arrays with EaCoN
authors:
  - Thibault Dayris
  - Bastien Job
input:
  - Cytoscan CEL file
output:
  - Complete EaCoN analysis
  - HTML report
notes: |
  notes
