---
name: SnpSift PhastCons
description:  Annotate using PhastCons with `SnpSift <https://pcingola.github.io/SnpEff/ss_phastcons/>`_
authors:
  - Thibault Dayris
input:
  - call: Calls that are to be annoated
  - phastcons: A PhastCons directory path
  - bed: Optional path to a bed file
output:
  - call: Annotated calls
note: |
  You can annotate intervals using BED files and -bed command line option. In the output BED formatted intervals, the score column (fifth column), is the average conservation score of all bases within the interval.
