channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-enrichplot=1.14.1
  - bioconda:bioconductor-clusterprofiler=4.2.0
  # - bioconda:r-cairo=1.5_9
  # - conda-forge:r-ggupset=0.2.1
