---
name: upsetplot_clusterprofiler
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-enrichplot=1.4.0
  - bioconda:bioconductor-clusterprofiler=3.12.0
  # - bioconda:r-cairo=1.5_9
  # - conda-forge:r-ggupset=0.2.1
