---
name: Upset plot
description: Draw a heatmap from enriched terms and GSEA
authors:
  - Thibault Dayris
input:
  - A RDS-formatted object containing enriched terms
output:
  - A upsetplot of enriched terms as a PNG image
notes: |
  Works on enrichment objects only.

  Parameters:
    * upsetplot_extra: Extra parameters for upsetplot, besides "x"
