---
name: lollipop plot
description: Draw lollipop plot from RDS-formatted maftools object
authors:
  - Thibault Dayris
input:
  - maf: Path to RDS formatted maftools object
output:
  - png: Path to png file
notes: |
  Use the "gene" wildcard to provide name of the gene of interest
