---
name: compare cluster
description: Compare enrichment on clusters of sample
authors:
  - Thibault Dayris
input:
  - gene_lists: A list of geneList objects as TSV
output:
  - rds: A RDS object containing the cluster comparison
  - tsv: A TSV file containing the cluster comparison
  - dotplot: A png containing dotplot cluster comparison
params:
  - fun: A function applied to each cluster. One of `groupGO`, `enrichGO`, `enrichKEGG`, `enrichDO` or `enrichPathway`.
  - condition: A dictionnary with `geneList.tsv -> Condition`
  - name: A dictionnary with `geneList.tsv -> name`
  - extra: Optional parameters given to the function set above, in `params.fun`.
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

