---
name: tx2gene
description: Build a transcript / gene correspondancy table from a GTF
authors:
  - Thibault Dayris
input:
  - A path to a GTF file
output:
  - A TSV-formatted text file containing all transcript with their gene name
notes: |
  Parameters:

  * header (bool): Weather to write column header or not
  * positions (bool): Weather to write positions or not
  * gencode (bool): Remove patch in ensembl identifiers

  The output file contains:

  +--------+--------------+----------+------------+----------+----------+
  | GeneID | TranscriptID | GeneName | Chromosome | Start    | Stop     |
  +========+==============+==========+============+==========+==========+
  | Awlays | Always       | Always   | Optional   | Optional | Optional |
  +--------+--------------+----------+------------+----------+----------+
