name: Pandas merge
description: Merge text tables with pandas
url: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html
authors:
  - Thibault Dayris
input:
  - tsv: A list of paths to TSV files
output:
  - Path to a TSV file
params:
  - read_extra: Dictionary of optional parameters to `pandas.read_csv()`
  - merge_extra: Dictionary of optional parameters to `pandas.merge()`
  - write_extra: Dictionary of optional parameters to `pandas.to_csv()`
