---
name: drop_md5_duplicates
description: |
  This wrapper checks for duplicates in a list of input, and
authors:
  - Thibault Dayris
input:
  - Any list of files. At least two files.
output:
  - Hash of the input files
notes: |
  Raises an error if input files are duplicated
