---
name: cancer gene census
description: Annotate maf files with Cancer Gene Sensus
url: https://cancer.sanger.ac.uk/census
authors:
  - Thibault Dayris
input:
  - maf: Path to maf file
  - sanger: Path to Cancer Gene Sensus file from sanger institute
output:
  - maf: Path to annotated maf file
notes: |
  This will load the whole input maf file in memory
