---
name: biseq
description: Analyse differentially methylated regions with BiSeq
authors:
  - Thibault Dayris
input:
  - bismark: CpG contextx from methylation extractor of bismark
output:
  - beta: TSV formatted table containing differentially methylated clusters
  - raw: Optional RDS-formatted BSraw object
  - covboxplot: Optional boxplot of the coverage of CpG-sites
  - clustersites: Optional table containing high density CpG cluster of regions
  - smooth_covboxplot: Optional boxplot of the coverage of smoothed CpG-sites
  - groupwise_scatterplot: Optional scatter plot giving the methilation level across two groups
notes: |
  notes
