channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-deseq2 ==1.32.0
  - bioconda::bioconductor-pcaexplorer ==2.18.0
  - bioconda::bioconductor-delayedarray ==0.18.0
  - conda-forge::r-readr ==1.4.0
  - conda-forge::r-jsonlite ==1.7.2
  - bioconda::bioconductor-summarizedexperiment ==1.22.0
  - bioconda::bioconductor-iranges ==2.26.0
  - conda-forge::cairo ==1.16.0
  - conda-forge::r-cairo ==1.5_12.2
  - bioconda::bioconductor-org.hs.eg.db ==3.13.0
  - bioconda::bioconductor-org.mm.eg.db ==3.13.0
