---
name: tsv to gene list
description: Build a clusterProfiler gene list from a TSV formatted table
authors:
  - Thibault Dayris
input:
  - A TV formatted table with ensembl genes identifiers
output:
  - A RDS-formatted gene list
notes: |
  Annotations available: GRCh38
