---
name: Variant Density
description: Compute and filter based on local variant density
authors:
  - Thibault Dayris
input:
  - A VCF formatted text file containing variant informations
output:
  - A VCF formatted text file with filtered data
notes: |
  The VCF is assumed to be sorted.

  Parameters:

  * window_size (int): The genomic range used to compute variant density. *Default: 150*
  * update_header (bool): Add the filtering information in the header. *Default: true.*
  * update_info (bool): Add density information in the info column. *Default: true.*
  * filter_vcf (bool): Remove the variants in a region which density is below the provided threshold. *Default: false.*
