---
name: rbt
description: compute stats on sequence file with `rust bio tools <>`_
authors:
  - Thibault Dayris
input:
  - A sequence file (fastq or fasta), gzipped or not
output:
  - A yaml file containing
notes: |
  Two threads are required when the input files are gzipped.

  The `--fastq` flag is set automatically.
