---
name: chipseeker
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2
  - bioconda:bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.10.0
  - bioconda:bioconductor-txdb.mmusculus.ucsc.mm10.knowngene=3.10.0
  - bioconda:bioconductor-txdb.mmusculus.ucsc.mm9.knowngene=3.2.2
  - bioconda:bioconductor-chipseeker=1.24.0
  - bioconda:bioconductor-clusterprofiler=3.16.0
