---
name: getTagMatrix
description: Load Peak files in R with ChipSeeker
authors:
  - Thibault Dayris
input:
  - A single peak file from macs2
output:
  - A RDS formatted file containing peaks
notes: |
  Set the genome annotation (hg19, hg38, mm9, mm10) with the txdb parameter.
  Additional organism shall be added on demand.
