---
name: GSEA GO
description: Perform GSE analysis on Gene Ontology
authors:
  - Thibault Dayris
input:
  - A geneList object as RDS
output:
  - A RDS object containing the GSEA based on GO
  - A TSV file containing the GSEA based on GO
notes: |
  The geneList object if described in the
  DESeq2_to_geneList wrapper

  Parameters:
    * gseGO_extra: Extra parameters for gseGO, besides "gene", "OrgDb", and "readable"
    * organism: Either Hs or Mm
