---
name: meta_caller
description: Use multiple callers to assess variants in a single sample
authors:
  - Thibault Dayris
input:
  - BAM formatted mapping files with their indexes files
  - FASTA formatted genome sequence, with their dict and fasta index
output:
  - Raw VCF files
notes: |
  This meta caller uses:

  * Varscan2 (snp + indel)
  * Mutect2
