name: decoys
url: https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/
description: Generate decoy sequences and gather their names
authors:
  - Thibault Dayris
input:
  - transcriptome: Path to transcriptome sequences, fasta/gz/bz2 formatted.
  - genome: Path to genome sequences, fasta/gz/bz2 formatted.
output:
  - gentrome: Path to fasta formatted gentrome. May be gzipped/bgzipped.
  - decoys: Path to text file contianing decoy sequence names.
notes: |
  Provide transcriptome and genome under the same format (raw fasta, gzipped
  or bgzipped). In case of compressed input, this wrapper required 2 threads,
  one for on-the-fly decompression and one for actual decoy sequences
  acquisition.
