---
name: vcf_format_to_info
description: Copy format information into info column to avoid issues whith GATK
authors:
  - Thibault Dayris
input:
  - call: A VCF with format fields
output:
  - call: A VCF with format fields copied to info
notes: |
  This fixes GATK VCF merge issues.
