---
name: wisecondorx gender
description: Returns gender according to the reference.
url: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#additional-functionality
authors:
  - Thibault Dayris
input:
  - test: Path to tested NPZ file
  - ref: Path to reference NPZ
output:
  - Predicted gender
