---
name: bs_ampliseq
description: Analyse bisulfite ampliseq with Bismark
authors:
  - Thibault Dayris
input:
  - Fastq files
output:
  - Bismark mapping + Methylation
usage:
  - cd /path/to/project
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/bs_ampliseq/run.sh
