---
name: DESeq2_to_geneList
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - r:r-base=3.6.1
  - bioconda:bioconductor-org.mm.eg.db=3.10.0
  - bioconda:bioconductor-org.hs.eg.db=3.10.0 
