channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-clusterprofiler=4.2.0
  - bioconductor-org.hs.eg.db=3.14.0
  - bioconductor-org.mm.eg.db=3.14.0
  - bioconductor-dose=3.20.0