---
name: DESeq2 to geneList
description: Converts a DESeq2 TSV formatted result into a geneList for clusterProfiler
authors:
  - Thibault Dayris
input:
  - A DESeq2 TSV formatted wald test result
output:
  - A RDS object containing the geneList
notes: |
  The geneList contains three features:

  * numeric vector: fold change or other type of numerical variable
  * named vector: every number was named by the corresponding gene ID
  * sorted vector: number should be sorted in decreasing order


  Parameters:

  * alpha_threshold: The padj threshold used to filter non significative events
