---
name: clusterp profiler
description: Run Gene set analyses with ClusterProfiler
authors:
  - Thibault Dayris
input:
  - List of differentially expressed genes
output:
  - Enrichment analysis against multiple databases
  - Multiple graphs
