---
name: hg38_genelist
url:
description: Create multiple Gene lists objects from a single TSV file
authors:
  - Thibault Dayris
input:
  - tsv: Path to TSV formatted stat changes
output:
  - tsv: List of TSV formatted stat changes, one per studied factor, with ENTREZID added and droped levels
  - rds: List of RDS formatted genelist objects.
notes: |
  The format of the genelist object is available in R.
  `library(clusterProfiler); data(geneList, package="DOSE")`

  The input TSV file looks like:

  .. list-table:: Desgin file format
    :widths: 33 33 33
    :header-rows: 1

    * - Ensembl_Gene_ID
      - Comparinson1
      - Optional comparison 2
      - ...
    * - ENSX000000XXXXXX
      - FoldChange/PAdj
      - FoldChange/PAdj
      - ...
    * - ENSX000000YYYYYY
      - FoldChange/PAdj
      - FoldChange/PAdj
      - ...
    * - ...
      - ...
      - ...
      - ...
