---
name: analyzeAlternativeSplicing
description: Predict alternative splicing
authors:
  - Thibault Dayris
input:
  - Switch list
output:
  - Switch list with alternative splicing predicted
notes: |
  The input switch list should have Sequence extracted, CPAT/Pfam results
  included, and should be tested for differential analysis result.
