name: cp (bash)
authors:
  - Thibault Dayris
description: Simple cp from bash.
input:
  - Any file.
output:
  - Any file.
notes: |
  Why ? I just wanted to test a simple case. Thus it's fair for hard copy over
  symbolic linking automatic choices
