---
name: vcf-annotate-dgidb
description: Looks for interacting drugs in `DGIdb <>`_ and annotates them for every gene in every record.
authors:
  - Thibault Dayris
input:
  - Callings (VCF, BCF)
output:
  - Annotated calls (VCF, BCF)
notes: |
  See a list of sources at: https://dgidb.org/api/v2/interaction_sources.json
