reference:
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta
  genome_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta.fai
  blacklist: /mnt/beegfs/database/bioinfo/Index_DB/blacklist/mm10.blacklist.nochr.bed

bowtie2:
  index: /mnt/beegfs/scratch/bioinfo_core/B22050_AMJO_01/data_output/cutntag/MappingPeakCalling/GRCm38