---
name: sed
description: Search and replace within a file
authors:
  - Thibault Dayris
input:
  - A text file
output:
  - The modified text file
notes: |
  Multiple modifications shall be provided at once, through sorted arrays.

  Some sed expression are already available and can be called in params:

  * csv_to_tsv (bool): Transform commas into tabs. This always appends first!
  * basename (bool): Remove all characters before "/" or "\" within a single column
  * wrap_lines (bool): Wrap lines at 80 characters
  * split_on_commas (bool): Split lines on commas
  * join_on_backslashes (bool): Write backslash separated lines on a single-one
  * join_on_spaces (bool): Join lines that start with whitespace

  Other sed expressions can be built manually
  * remove_list (list[str]): Remove all lines containing one of the strings provided
  * remove_lines (list[int]): Remove all lines which numbers are provided
  * replace_dict (dict[str, str]): A dictionnary in which key = replaced string, value = replacement string.
