---
name: "k-means sample clustering"
description: Run and plot K-Means clustering on a count table
authors:
  - Thibault Dayris
input:
  - count: Count table (TSV)
output:
  - png: Scatterplot displaying clustering results
  - csv: TSV table containing clustering results
params:
  - read_csv: Dictionnary containing pandas.read_csv arguments
notes: |
  notes
