---
name: Left_Minus_Join
description: Perform a left minus join between tables
authors:
  - Thibault Dayris
input:
  - Two dataframes
output:
  - One dataframe containing left minus join
notes: |
  Use `index` parameter to set the index column(s).
