---
name: simplify_enrichment
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::bioconductor-simplifyenrichment==1.0.0
  - bioconda::bioconductor-gosemsim==2.16.0
  - bioconda::bioconductor-org.hs.eg.db==3.12.0
  - conda-forge::r-magick==2.6.0
