---
name: GO_similarity
description: Load GO enriched terms, compute similarity on them and simplify the results
authors:
  - Thibault Dayris
input:
  - A TSV formatted file containing GO terms
output:
  - An optional RDS-formatted simplified object
  - An optional RDS-formatted similarity object
  - An optional TSV-formatted simplified table
  - An optional TSV-formatted similarity table
  - A PNG image of the simplified similarity table
notes: |
  Parameters:

  * terms_col: Name of the column containing GO-terms
