---
name: mutational_context
description: Compute mutational context
authors:
  - authors
input:
  - VCF as VRanged RDS object
  - Fasta file as RDS object
output:
  - RDS object containing variants with mutational context
notes: |
  See VariantAnnotation and Rsamtools wrappers for input requirements.
