---
name: TCN_GIS_autoscorer
description: Score genomic instability based on ASCN models
authors:
  - Thibault Dayris
  - Bastien Job
input:
  - An EaCoN gamma evaluation
output:
  - A TSV formatted instability table
