---
name: motifMatrix
description: Build a motif matrix from VRanges object
authors:
  - Thibault Dayris
input:
  - RDS formatted VRange object
output:
  - RDS formatted motifMatrix
  - TSV formatted motifMatrix
notes: |
  Output are optional
