name: complement
description: |
  Compute all genomic intervals that are not covered by at least
  one record from the input file.
authors:
  - Thibault Dayris
input:
  - BED/GFF/VCF formatted intervals
  - genome intervals
output:
  - BED formatted complement
notes: |
  Eventhough it is not mentionned in the official documentation:

  * GTF seems to be accepted as well as GFF.
  * genome intervals is a two columned bed file.
