name: bedtools complement
url: https://bedtools.readthedocs.io/en/latest/content/tools/complement.html
description: >
  Maps all regions of the genome which are not covered by the input.
url: https://bedtools.readthedocs.io/en/latest/content/tools/complement.html
authors:
  - Antonie Vietor
input:
  - in_file: BED/GFF/VCF files
  - genome: genome file (`genome file format <https://bedtools.readthedocs.io/en/latest/content/general-usage.html#genome-file-format>`_)
output:
  - complemented BED/GFF/VCF file, must be the first element in the output list
params:
  - extra: Optional parameters
