---
name: cpat
description: Assess coding potential
authors:
  - Thibault Dayris
input:
  - Hexamer table
  - Legit model
  - Transcript sequences (FASTA) or coordinate (BED)
  - Reference genome is transcript coordinates were provided
output:
  - TSV formatted coding potential assessment
