---
name: read peak file hg38
description: Load Peak files in R with ChipSeeker for hg38
authors:
  - Thibault Dayris
input:
  - tagmatrix: A RDS-formatted TagMatrix object
output:
  - png: A PNG formatted heatmap
params:
  - extra: Optional parameters for tagHeatmap function
