---
name: msisensor pro msi
description: Search for micro satellites in tumor vs normal
url: https://github.com/xjtu-omics/msisensor-pro/wiki/Key-Commands#msi-from-msisensor
authors:
  - Thibault Dayris
input:
  - microsat: Path to homopolymer files
  - normal: Path to normal bam
  - tumor: Path to tumor bam
output:
  - Path to MSI results
notes: |
  This tools directly comes from msisensor.
