---
name: RNASeq
description: Perform various analyses on RNASeq-bulk
authors:
  - Thibault Dayris
input:
  - Fastq files
output:
  - DGE + Fusions + reports
usage:
  - \# Go to your directory containing Fastq files
  - cd /path/to/project
  - \# Copy/paste the following line for **HG38**
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/rnaseq/run.sh
