---
name: mixcr assemble contigs
url: https://docs.milaboratories.com/mixcr/reference/mixcr-assembleContigs/
description: Assembles longest possible TCR/Ig receptor contig sequences.
authors:
  - Thibault Dayris
input:
  - Clones (clna) from mixcr
output:
  - clns: Assembled clones
  - report: txt assembly report
  - json: json assembly report
notes: |
  It is strongly encouraged to name your output file: *.clna when the `-a/--write-alignments` is used, and *.clns otherwise.
