name: sleuth_results
description: |
  Extract human readable results from a Sleuth object
authors:
  - Thibault Dayris
input:
  - RDS formatted sleuth object containing wald tests
output:
  - TSV formatted result table
note: |
  A separate extraction is performed for each beta within the sleuth object.
  Do not set "test" parameter.
