---
name: variant occurence cohort
description: Compute the occurence of a variant in a cohort
authors:
  - Thibault Dayris
input:
  - calls: A list of vcf files
  - occurence: A text file with occurence of each variant
output:
  - calls: A list of annotated VCF
notes: |
  notes
