---
name: analyzeCPAT
description: Add CPAT analysis to switch list
authors:
  - Thibault Dayris
input:
  - Swtich list
  - CPAT results
output:
  - Switch list with CPAT results included
notes: |
  Parameters:
    * extra: Optional parameters passed to importIsoformExpression, besides "switchAnalyzeRlist" and "pathToCPATresultFile"
