channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python ==3.9.6
  - pandas ==1.3.1
  - numpy ==1.21.1
  - seaborn ==0.11.1
  - matplotlib ==3.4.2
  - pillow ==8.3.1
  - pyqt ==5.12.3
  - sklearn-contrib-lightning ==0.6.0
  - scipy ==1.7.0
  - pip ==21.2.1
  - pip:
    - pykka
