---
name: kmeans
url: https://h1ros.github.io/posts/k-means-clustering/
description: Perform K-Means clustering and plot elbow graph
authors:
  - Thibault Dayris
input:
  - tsv: TSV formatted matrix
output:
  - distance_tsv: Clusterised distance matrix
  - kmeans: K-Means scatter plots
  - distance: Distance matrix plot
  - elbow: Elbow plot
params:
  - max_cluster: Maximum number of clusters tested (default 5)
  - read_csv: Arguments for csv reader (besides sep, and path)
notes: |
  While any kind of distance metrics provided by scipy.metrics.distance.pdist
  are available in this wrapper, euclidian distance works the best with gene
  expression and K-Means.
