---
name: msisensor pro scan
description: Scan genome in search of microsatellites
url: https://github.com/xjtu-omics/msisensor-pro/wiki/Key-Commands#scan-from-msisensor
authors:
  - Thibault Dayris
input:
  - Path to reference genome
output:
  - Path to homopolymer file
notes: |
  This tools directly comes from msisensor.
