name: gatk CollectSequencingArtifactMetrics
description: |
  Run gatk CollectSequencingArtifactMetrics to estimate sequencing bias
authors:
  - Thibault Dayris
input:
  - Bam formatted mapped reads
  - Optional dbSNP (vcf.gz) with its tabix index aside
  - Optional interval (bed) file
output:
  - Bias metrics files under expected format (default = txt)
notes: |
  * The `java_opts` param allows for additional arguments to be passed to the java compiler, e.g. "-Xmx4G" for one, and "-Xmx4G -XX:ParallelGCThreads=10" for two options.
  * The `extra` param alllows for additional program arguments.
  * For more inforamtion see, https://software.broadinstitute.org/gatk/documentation/article?id=11050
  * WARNING: provide output prefix as a parameter named "prefix", or let "*.pre_adapter_detail_metrics" be your first result
