name: picard CleanSam
description: |
  Cleans the provided SAM/BAM, soft-clipping beyond-end-of-reference alignments and setting MAPQ to 0 for unmapped reads
authors:
  - Thibault Dayris
input:
  - sam/bam file
output:
  - cleaned sam/bam file
