name: DeepTools bamCoverage
description: |
  Generate a coverage track from alignment of reads or fragments
authors:
  - Thibault Dayris
input:
  - BAM formatted alignment file
  - Optional black list file
output:
  - Coverage track (bigWig or bedGraph)
notes: |
  You can specify regions in the file name. See example
