extra:
  EaCoN_ascn: force = TRUE
  EaCoN_gis: ''
  EaCoN_process: apt.build = "na33.r2", force = TRUE
  EaCoN_segment: segmenter = "ASCAT", smooth.k = NULL, BAF.filter = 0.9, SER.pen =
    40, nrf = 0.5, penalty = 50, force = TRUE
params:
  arraytype: OncoScan_CNV
  genome: hg19
  nar: na33.r2
  segmenter: ASCAT
samples: []
