---
name: isoformSwitchTestDEXSeq
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  -  bioconda:bioconductor-isoformswitchanalyzer=1.8.0
  - bioconda:bioconductor-dexseq=1.34.0 
