---
name: isoformSwitchTestDEXSeq
description: Testing for Isoform Switches via DEXSeq
authors:
  - Thibault Dayris
input:
  - SwitchList from imported isoform expression (filtered or not)
output:
  - Isoform switches
notes: |
  Parameters:
    * extra: Optional parameters passed to importIsoformExpression, besides "switchAnalyzeRlist"
