name: bcftools mpileup
url: https://samtools.github.io/bcftools/bcftools.html#mpileup
description: Generate VCF or BCF containing genotype likelihoods for one or multiple alignment (BAM or CRAM) files with `bcftools mpileup <https://samtools.github.io/bcftools/bcftools.html#mpileup>`_.
authors:
  - Michael Hall
input:
  - alignments: List of paths to bam-formatted almignments
output:
  - pileup: Path to pileup result file
params:
  - options: Optional parameters
notes: |
  * Add --regions and --samples-files through params.options
  * The `uncompressed_bcf` param allows to specify that a BCF output should be uncompressed (ignored otherwise).
  * The `extra` param allows for additional program arguments (not `--threads`, `-f/--fasta-ref`, `-o/--output`, or `-O/--output-type`).
