---
name: TSV_to_geneList
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge::r-base==4.0.3
  - bioconda::bioconductor-org.hs.eg.db==3.12.0
  - bioconda::bioconductor-annotationdbi==1.52.0
