---
name: TSV to genelist (HG38)
description: Converts a TSV-formatted differential gene analysis to a GeneList object
authors:
  - Thibault Dayris
input:
  - A TSV formatted DGE result
output:
  - A RDS object containing the geneList
notes: |
  The geneList contains three features:

  * numeric vector: fold change or other type of numerical variable
  * named vector: every number was named by the corresponding gene ID
  * sorted vector: number should be sorted in decreasing order


  Parameters:

  * alpha_threshold: The padj threshold used to filter non significative events
  * fc_threshold: The fold change threshold used to filter non significative events
  * keytype: The type of genes identifiers used in DGE (ENSEMBL, SYMBOL, ...)
  * gene_id: the column that contains gene identifiers (or gene names, ...)
  * fold_change: the column containing fold changes (or stat change, ...)
  * padj: the column containing adjusted pvalues (or qvalues, ...)
