---
name: Seaborn
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge:python=3.9.0
  - conda-forge:pandas=1.1.3
  - conda-forge:numpy=1.19.2
  - conda-forge:seaborn=0.11.0
  - conda-forge:matplotlib=3.3.2
  - conda-forge:pillow=8.0.0
  - conda-forge:pyqt=5.12.3
