---
name: displot
description: Perform a distribution plot with Seaborn
authors:
  - Thibault Dayris
input:
  - a TSV formatted table
output:
  - A PNG formatted distribution
notes: |
  Use extra parameters to fill distplot arguments
