channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda::bioconductor-maftools==2.6.0
  - conda-forge::r-nmf==0.21.0
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg38==1.4.3
