---
name: pandas_histogram
description: Plot a pandas histogram
authors:
  - Thibault Dayris
input:
  - TSV table
output:
  - png image
notes: |
  Parameters:

  * extra: dict of parameters to pass to pandas.DataFrame.hist()
