---
name: Barplot
description: Draw a bar plot from enriched terms
authors:
  - Thibault Dayris
input:
  - A RDS-formatted object containing enriched terms
output:
  - A barplot of enriched terms as a PNG image
notes: |
  Use clusterProfiler enrichXXX to get enriched terms. This may also be used
  with gseXXX, but you might want to consider GSEA-like plots.

  Parameters:
    * barplot_extra: Extra parameters for barplot
