---
name: mixcr align
description: align raw sequencing reads to reference V, D, J and C genes of T- and B- cell receptors with `mixcr <https://mixcr.readthedocs.io/en/master/align.html>`_
authors:
  - Thibault Dayris
input:
  - Sequences in Fasta or Fastq formats, gzipped or not.
output:
  - Alignments
