---
name: mixcr align
url: https://docs.milaboratories.com/mixcr/reference/mixcr-align/
description: align raw sequencing reads to reference V, D, J and C genes of T- and B- cell receptors.
authors:
  - Thibault Dayris
input:
  - Sequences in Fasta or Fastq formats, gzipped or not.
output:
  - report: txt alignment report
  - json: json alignment report
  - vdjca: alignment
params:
  - extra: Optional parameters
  - species: Name of the organism. 
notes: |
  For species name, see: https://github.com/repseqio/library-imgt/releases