name: SnpSift rm info
url: https://pcingola.github.io/SnpEff/ss_rminfo/
description:  Convert from VCF to TSV with `SnpSift <https://pcingola.github.io/SnpEff/ss_rminfo/>`_
authors:
  - Thibault Dayris
input:
  - VCF file to remove the given info fields
output:
  - VCF file with given info field removed
params:
  - extra: Extra parameters
  - rminfo: List of info fields to remove

