---
name: awk
description: Run any awk scripts easily
authors:
  - Thibault Dayris
input:
  - Path to an input text file
output:
  - Path to an output text file
params:
  - begin: List of Awk BEGIN instructions. They will be separated by semi-columns.
  - body: List of Awk core instructions. They will be separated by semi-columns.
  - end: Awk END instructions. They will be separated by semi-columns.
notes: |
  notes
