---
name: plot_maf_summary
description: Plot multiple metrics on a MAF file with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_
authors:
  - Thibault Dayris
input:
  - A RDS-formatted maftools object
output:
  - A PNG-formatted summary plot
notes: |
  Use "maftools_extra" to provide parameters to `maftools::plotmafSummary`, and
  "png_extra" to provide extra parameters to `grDevices::png`.
