---
name: wisecondorx predict
description: Predict copy number alterations
url: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#stage-3-predict-copy-number-alterations
authors:
  - Thibault Dayris
input:
  - test: Path to sample NPZ
  - ref: Path to reference NPZ
output:
  - bins: all bin-wise information
  - segments: all segment-wise information
  - aberrations: aberrant segments, defined by the `--beta` or `--zscore` parameters.
  - statistics: per chromosome and overall statistics.
params:
  - extra: Extra parameters for WisecondorX predict
  - prefix: Result prefix
