name: sleuth_wald_test
description: |
  Perform a Wald Test
authors:
  - Thibault Dayris
input:
  - RDS formatted sleuth object
output:
  - RDS formatted sleuth object with wald test performed
note: |
  A separate test is run for each beta within the sleuth object.
  Do not set "which_beta" parameter.
