---
name: mutect2_somatic
description: Call variants on BAM files with Mutect2, considering a pair of bam file.
authors:
  - Thibault Dayris
input:
  - Tumor Bam-formatted mapped reads
  - Normal Bam-formatted mapped reads
output:
  - VCF formatted raw variants from Mutect2
notes: |
  Bam are expected to be mate-fixed (see bwa_fixmate meta-wrapper).
