---
name: tximeta
url: https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.html#Running_tximeta
description: Import count estimates in R with tximeta
authors:
  - Thibault Dayris
input:
  - json: Optional path to a linked txome, see tximeta/makelinkedtxome
  - coldata: Path to coldata file, a TSV describing samples, their belonging conditions and the path a their quantification files/dirs.
output:
  - rds: Optional path to summarized experiment object, with default estimates.
  - gene_rds: Optional path to summarized experiment object, with counts estimates summarized to genes.
params:
  - extra: Optional parameters for function `tximeta::tximeta(...)`
  - summarize_to_gene_extra: Optional parameters for function `tximeta::summarizeToGene(...)`
notes: |
  Without a json file, the aggregation from transcripts estimates to gene estimates is not possible.
