---
name: plot_genes
description: Plot gene information (dispersions, expression, ...) to help DESeq2 understanding
authors:
  - Thibault Dayris
input:
  - intermediar: Path to TSV formatted `mcols(dds)`
  - wald: Path to TSV formatted `DESeq(dds)`
  - mu: path to TSV formatted `assays(dds)[["mu"]]`
  - cooks: path to TSV formatted `assays(dds)[["cooks"]]`
output:
  - expression: Path to PNG expression plot
params:
  - condition_dict: `{sample: condition, ...}` This will be used to define color scheme and categories
