---
name: tximport_deseq2
description: Import counts with tximport and run DESeq2
authors:
  - Thibault Dayris
input:
  - Counts from Salmon, Kallisto, RSEM, Star ...
output:
  - RDS-formatted DESeq2 results
  - TSV fromatted DESeq2 results
  - TSV formatted normalized count table
notes: |
  The R statistical formula must refer to columns in design file.
