---
name: IGR_Copy
description: Copy/Softlink/concat files, either from an absolute path or iRODS ones.
authors:
  - Thibault Dayris
input:
  - Optional source path(s) to the copied file(s)
output:
  - Destination path(s) of the copied file(s)
params:
  - extra: Optional parameters for bash `cp`
  - extra_irods: Optional parameters for irods `iget`
notes: |
  iRODS paths should be provided in parameters.

  Give either a python list of paths to have separate files at the end, or
  a comma separated list of files to concatenate each of them!
