---
name: IGR_Copy
description: Copy/Softlink/concat files, either from an absolute path or iRODS ones.
authors:
  - Thibault Dayris
input:
  - Optional source path to the copied file
output:
  - Destination path of the copied file
notes: |
  iRODS paths should be provided in parameters.

  Give either a python list of paths to have separate files at the end, or
  a comma separated list of files to concatenate each of them!
