---
name: Signatures
description: |
  Extrat given signature from a trinucleotide matrix,
  compare them and plot cosine similarities with `maftools <https://bioconductor.org/packages/release/bioc/html/maftools.html>`_
authors:
  - Thibault Dayris
input:
  - A RDS-formatted trinucleotide matrix object
output:
  - An optional RDS-formatted extracted-signatures file
  - An optional PNG-formatted extracted-signatures file
notes: |
  For input, use maftools/trinucleotidematrix

  Use "sig_extra" to provide parameters to `maftools::extractSignatures`.
