---
name: Revel to VCF
description: Format REVEL database to match the VCF INFO field format
authors:
  - Thibault Dayris
input:
  - Path to Revel database file
output:
  - Path to Revel VCF-ized
notes: |
  notes
